### ISSUE TITLE
启动hello world，模拟器空白，日志提示json语法错误

### ISSUE THREAD

**Issue by cnfczn** [msojocs/wechat-web-devtools-linux#101]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，新建空模板项目；
2. HelloWorld不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**
启动hello world项目，调试器 Console报错：
[ WXML 文件编译错误] 
Error: parse result json content fail: SyntaxError: Unexpected token / in JSON at position 0(env: Linux,mp,1.06.2308310; lib: 3.2.4)
模拟器空白，没有输出
真机调试正常，但是IDE左侧模拟器空白

**问题复现**
1. 新建本地项目
2. 空模板，不使用云开发
3. 打开后就这样了

**期望的效果**

**截屏**
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/1464805/147e3c42-1481-488a-86df-c1a1db544d81)
**1.06.2308310:**
 - OS: gnetoo
 - appimage版本

**Comment by cnfczn** [comment]
刚又试了下，发现本地设置-调试基础库>=3.0.2就会出现这个错误，现在改用2.33.0正常了。

**Comment by msojocs** [comment]
没有复现报错。

不过，>=3.0.2会helloword会白屏，正常项目倒是没问题。

暂时不管。

**Comment by igo312** [comment]
> 刚又试了下，发现本地设置-调试基础库>=3.0.2就会出现这个错误，现在改用2.33.0正常了。 不确定这算不算bug。

同样使用js空白模板开发，使用的基础库是3.6.5，改用2.24.7可以正常渲染，错误信息如下

`[ WXML 文件编译错误]  undefined(env: Linux,mp,1.06.2409140; lib: 3.6.5)`
