### ISSUE TITLE
报错 Uncaught SyntaxError: Unexpected token ']' 和Uncaught ReferenceError: $gwx is not defined

### ISSUE THREAD

**Issue by liushuai05** [msojocs/wechat-web-devtools-linux#102]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）： 不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**
项目无法渲染提示 Uncaught SyntaxError: Unexpected token ']'  和Uncaught ReferenceError: $gwx is not defined,并且加载到任何api请求
**问题复现**

1. 打开项目
2. 点击  编译
3. 看到问题

**期望的效果**
希望能正常出现加载中图标,并能正常调用api接口

**截屏**
![微信图片编辑_20231223135656](https://github.com/msojocs/wechat-web-devtools-linux/assets/26994692/216d1c0e-e2e2-4b97-92b7-362017b970ed)
![2023-12-23_13-55_1](https://github.com/msojocs/wechat-web-devtools-linux/assets/26994692/b33e1261-fe56-4f03-874c-c9e0be0c0619)
![2023-12-23_14-19](https://github.com/msojocs/wechat-web-devtools-linux/assets/26994692/e61bf718-a924-4889-9610-3a17312fb471)

**版本信息 (这是必要的):**
 - OS: e.g. manjaro  
 - Wine Version: e.g. 7 可选
- wechat-web-devtools-linux  Version : WeChat_Dev_Tools_v1.06.2308310-2_x86_64_linux.AppImage
**代码片段**
 - Package:   
 - 链接: https://pan.baidu.com/s/1WKe6NDVYhmPHl7Q1lLZOMg 提取码: wce3

**Comment by msojocs** [comment]
已复现

**Comment by msojocs** [comment]
麻烦试一下：https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/continuous

**Comment by liushuai05** [comment]
> 麻烦试一下：https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/continuous

已正常,非常感谢大佬百忙中抽出时间处理
