### ISSUE TITLE
请教一下，有没有办法在使用appimage的情况下调用wechat-devtools-cli

### ISSUE THREAD

**Issue by liushuai05** [msojocs/wechat-web-devtools-linux#103]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**
请教一下，有没有办法在使用appimage的情况下调用wechat-devtools-cli呢大佬
由于这边搭建开发环境一直报pyg错误，准备放弃开发版本了，想一直使用appimage，但是有用到自动命令行提交代码，以及uniapp开发环境需要频繁打开开发工具这边之前是写了个sh文件自动关闭然后再指定目录打开开发工具，所以一定程度上需要依赖cli的加持。希望大佬能解惑。
不好意思，不小心点成了bug提交。

**Comment by msojocs** [comment]
目前应该不支持，但是应该能通过命令行参数实现。
类似这样：
`xxx.appimage cli ...cmds`

**Comment by liushuai05** [comment]
> 目前应该不支持，但是应该能通过命令行参数实现。 类似这样： `xxx.appimage cli ...cmds`

看了一下  cli ...cmds目前确实可以用 感谢大佬

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/f5edfbc2-41f0-4075-b645-2d3859c412ca)

哦，确实有这个，给忘了。

**Comment by liushuai05** [comment]
> ![image](https://private-user-images.githubusercontent.com/20937135/292819461-f5edfbc2-41f0-4075-b645-2d3859c412ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1NzYxOTIsIm5iZiI6MTcwMzU3NTg5MiwicGF0aCI6Ii8yMDkzNzEzNS8yOTI4MTk0NjEtZjVlZGZiYzItNDFmMC00MDc1LWI2NDUtMmQzODU5YzQxMmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA3MzEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1YzA5ZDg3NDhlMWNiNzUzY2Y0Y2I3MDY5OTRhYjc2NTRkYzBiYTg5N2JkZWUyMTRmMzU1YTdjMmVkOTllZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5dbBL3Mtl86k7Is820vQ1smrtdZvj6xMHNGSltGufAQ)
> 
> 哦，确实有这个，给忘了。

嗯嗯 是的  希望大佬能抽业余时间 帮忙看一下这个闪退能否修复  万分感谢

**Comment by msojocs** [comment]
最新版已处理cli闪退问题。

**Comment by liushuai05** [comment]
> 最新版已处理cli闪退问题。
好像少了个空格大佬
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/26994692/f798fbad-9fe6-484e-af58-d3634da82bb0)

**Comment by msojocs** [comment]
尬住，我改一下

**Comment by liushuai05** [comment]
> 尬住，我改一下

不急 大佬有时间了处理就行   上次的捐曾应该收到了吧  我准备再捐点  可能没多少 一点点心意  大佬辛苦了 哈哈哈

**Comment by msojocs** [comment]
有收到，感谢
