### ISSUE TITLE
docker-compose up错误，gyp built error

### ISSUE THREAD

**Issue by luowa-technology** [msojocs/wechat-web-devtools-linux#106]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**

docker-compose up报错，有关gyp

**问题复现**
sudo docker-compose up

**期望的效果**
devtools constructed

**截屏**
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/164145506/d3c22186-cf14-4231-906b-c9dec171f08c)

**版本信息 (这是必要的):**
 - OS:debian 12
 - Package:wine-8.0 (Debian 8.0~repack-4)

**代码片段**
wechat_devtools_1  |  ######## 版本信息 2024-03-20 07:28:22 ########
wechat_devtools_1  | NW VERSION: 0.55.0
wechat_devtools_1  | nw-gyp version: v3.6.6
wechat_devtools_1  | node version: v16.4.2
wechat_devtools_1  | npm version: 7.18.1
wechat_devtools_1  | Python 2.7.12
wechat_devtools_1  | Python 3.6.5
wechat_devtools_1  | rg
wechat_devtools_1  |  install modules  
wechat_devtools_1  | npm WARN deprecated har-validator@5.1.5: this library is no longer supported
wechat_devtools_1  | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
wechat_devtools_1  | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
wechat_devtools_1  | npm WARN deprecated node-pre-gyp@0.13.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
wechat_devtools_1  | npm WARN deprecated spdlog@0.11.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
wechat_devtools_1  | npm ERR! code 1
wechat_devtools_1  | npm ERR! path /workspace/package.nw/node_modules_tmp/node_modules/native-watchdog
wechat_devtools_1  | npm ERR! command failed
wechat_devtools_1  | npm ERR! command sh -c node-gyp rebuild
wechat_devtools_1  | npm ERR! make: Entering directory '/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog/build'
wechat_devtools_1  | npm ERR!   CXX(target) Release/obj.target/watchdog/src/watchdog.o
wechat_devtools_1  | npm ERR! watchdog.target.mk:111: recipe for target 'Release/obj.target/watchdog/src/watchdog.o' failed
wechat_devtools_1  | npm ERR! make: Leaving directory '/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog/build'
wechat_devtools_1  | npm ERR! gyp info it worked if it ends with ok
wechat_devtools_1  | npm ERR! gyp info using node-gyp@4.0.0
wechat_devtools_1  | npm ERR! gyp info using node@16.4.2 | linux | x64
wechat_devtools_1  | npm ERR! (node:191) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
wechat_devtools_1  | npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
wechat_devtools_1  | npm ERR! gyp info spawn /usr/bin/python2
wechat_devtools_1  | npm ERR! gyp info spawn args [
wechat_devtools_1  | npm ERR! gyp info spawn args   '/workspace/package.nw/node_modules_tmp/node_modules/node-gyp/gyp/gyp_main.py',
wechat_devtools_1  | npm ERR! gyp info spawn args   'binding.gyp',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-f',
wechat_devtools_1  | npm ERR! gyp info spawn args   'make',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-I',
wechat_devtools_1  | npm ERR! gyp info spawn args   '/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog/build/config.gypi',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-I',
wechat_devtools_1  | npm ERR! gyp info spawn args   '/workspace/package.nw/node_modules_tmp/node_modules/node-gyp/addon.gypi',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-I',
wechat_devtools_1  | npm ERR! gyp info spawn args   '/home/user/.node-gyp/16.4.2/include/node/common.gypi',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dvisibility=default',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/user/.node-gyp/16.4.2',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/workspace/package.nw/node_modules_tmp/node_modules/node-gyp',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/user/.node-gyp/16.4.2/<(target_arch)/node.lib',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dmodule_root_dir=/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_engine=v8',
wechat_devtools_1  | npm ERR! gyp info spawn args   '--depth=.',
wechat_devtools_1  | npm ERR! gyp info spawn args   '--no-parallel',
wechat_devtools_1  | npm ERR! gyp info spawn args   '--generator-output',
wechat_devtools_1  | npm ERR! gyp info spawn args   'build',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Goutput_dir=.'
wechat_devtools_1  | npm ERR! gyp info spawn args ]
wechat_devtools_1  | npm ERR! gyp info spawn make
wechat_devtools_1  | npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 12 ]
wechat_devtools_1  | npm ERR! In file included from ../src/watchdog.cc:9:0:
wechat_devtools_1  | npm ERR! /home/user/.node-gyp/16.4.2/include/node/uv.h:24:0: error: unterminated #ifndef
wechat_devtools_1  | npm ERR!  #ifndef UV_H
wechat_devtools_1  | npm ERR!  ^
wechat_devtools_1  | npm ERR! In file included from ../src/watchdog.cc:9:0:
wechat_devtools_1  | npm ERR! /home/user/.node-gyp/16.4.2/include/node/uv.h:751:34: error: 'uv_' was not declared in this scope
wechat_devtools_1  | npm ERR!  UV_EXTERN int uv_tty_get_winsize(uv_
wechat_devtools_1  | npm ERR!                                   ^
wechat_devtools_1  | npm ERR! ../src/watchdog.cc:122:40: error: expected '}' at end of input
wechat_devtools_1  | npm ERR!  NAPI_MODULE(NODE_GYP_MODULE_NAME, Init);
wechat_devtools_1  | npm ERR!                                         ^
wechat_devtools_1  | npm ERR! make: *** [Release/obj.target/watchdog/src/watchdog.o] Error 1
wechat_devtools_1  | npm ERR! gyp ERR! build error 
wechat_devtools_1  | npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
wechat_devtools_1  | npm ERR! gyp ERR! stack     at ChildProcess.onExit (/workspace/package.nw/node_modules_tmp/node_modules/node-gyp/lib/build.js:262:23)
wechat_devtools_1  | npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
wechat_devtools_1  | npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
wechat_devtools_1  | npm ERR! gyp ERR! System Linux 6.1.0-15-amd64
wechat_devtools_1  | npm ERR! gyp ERR! command "/workspace/node/bin/node" "/workspace/package.nw/node_modules_tmp/node_modules/.bin/node-gyp" "rebuild"
wechat_devtools_1  | npm ERR! gyp ERR! cwd /workspace/package.nw/node_modules_tmp/node_modules/native-watchdog
wechat_devtools_1  | npm ERR! gyp ERR! node -v v16.4.2
wechat_devtools_1  | npm ERR! gyp ERR! node-gyp -v v4.0.0
wechat_devtools_1  | npm ERR! gyp ERR! not ok
wechat_devtools_1  | 
wechat_devtools_1  | npm ERR! A complete log of this run can be found in:
wechat_devtools_1  | npm ERR!     /workspace/cache/npm/node_cache/_logs/2024-03-20T07_28_26_284Z-debug.log
wechat_devtools_1  |  失败  command: "$root_dir/tools/rebuild-node-modules.sh" "$nwjs_version"
wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:156
wechat_devtools_1  |   at 
wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1  |   at docker/entrypoint:29
wechat_devtools_1  |   at 
wechat-web-devtools-linux_wechat_devtools_1 exited with code 1
(base) jorden@jorden-V6.1.0-15-amd64:~/Softwares/web/wechat-web-

**额外的信息**
这里显示需要路径/usr/bin/python2.但是python2在debian12被移除

**Comment by msojocs** [comment]
我这边是没问题的，请删除cache文件夹后重试。
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/c1d237e4-7b67-4ade-af70-de00cab0088f)

**Comment by luowa-technology** [comment]
删除cache文件夹后报错：
wechat_devtools_1  |  fix terminal  
wechat_devtools_1  | Terminal启动位置: 
wechat_devtools_1  |  警告  Terminal启动位置未找到wechat_devtools_1  | wcc: /workspace/tmp/core/core.wxvpkg/b3576fd22b50987906da218d3aa0a7cd.js
wechat_devtools_1  | env: /workspace/tmp/core/core.wxvpkg/37afa82859c8c2ff0f4fc82f8e4ef83a.js
wechat_devtools_1  | /workspace/tmp/core/core.wxvpkg/5599c40fc3e706fdfdf41f1b3082b524.js
wechat_devtools_1  |  fix theme  
wechat_devtools_1  | theme: /workspace/tmp/core/core.wxvpkg/c729e63337ab0f2ce90297a1b8925f95.js
wechat_devtools_1  |  fix update check  
wechat_devtools_1  |  pack  
wechat_devtools_1  | /workspace/package.nw/core.wxvpkg
wechat_devtools_1  |  Rebuilding wechat-devtools node modules  
wechat_devtools_1  | =======请安装nw-gyp=======
wechat_devtools_1  |  失败  command: "$root_dir/tools/rebuild-node-modules.sh" "$nwjs_version"
wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:156
wechat_devtools_1  |   at 
wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1  |   at docker/entrypoint:29
wechat_devtools_1  |   at 
wechat-web-devtools-linux_wechat_devtools_1 exited with code 1

**Comment by luowa-technology** [comment]
> 我这边是没问题的，请删除cache文件夹后重试。 ![image](https://private-user-images.githubusercontent.com/20937135/314423588-c1d237e4-7b67-4ade-af70-de00cab0088f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzUxMDksIm5iZiI6MTcxMDkzNDgwOSwicGF0aCI6Ii8yMDkzNzEzNS8zMTQ0MjM1ODgtYzFkMjM3ZTQtN2I2Ny00YWRlLWFmNzAtZGUwMGNhYjAwODhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDExNDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZGJmNGNkZTEzMDQ3NGQzNDJjNGEyMzNiNzk1ZmI2NmE3MDA0MzlhNmQ3MDM3Njc2OTU5MDFkZTM2NjEyMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xq9xc5shUp9w4dkZpSBeLqPnFzyWH-Fzt3R9UC_40T0)

删除cache文件夹后报错：
wechat_devtools_1 | fix terminal
wechat_devtools_1 | Terminal启动位置:
wechat_devtools_1 | 警告 Terminal启动位置未找到wechat_devtools_1 | wcc: /workspace/tmp/core/core.wxvpkg/b3576fd22b50987906da218d3aa0a7cd.js
wechat_devtools_1 | env: /workspace/tmp/core/core.wxvpkg/37afa82859c8c2ff0f4fc82f8e4ef83a.js
wechat_devtools_1 | /workspace/tmp/core/core.wxvpkg/5599c40fc3e706fdfdf41f1b3082b524.js
wechat_devtools_1 | fix theme
wechat_devtools_1 | theme: /workspace/tmp/core/core.wxvpkg/c729e63337ab0f2ce90297a1b8925f95.js
wechat_devtools_1 | fix update check
wechat_devtools_1 | pack
wechat_devtools_1 | /workspace/package.nw/core.wxvpkg
wechat_devtools_1 | Rebuilding wechat-devtools node modules
wechat_devtools_1 | =======请安装nw-gyp=======
wechat_devtools_1 | 失败 command: "$root_dir/tools/rebuild-node-modules.sh" "$nwjs_version"
wechat_devtools_1 | at ./tools/setup-wechat-devtools-bash:156
wechat_devtools_1 | at
wechat_devtools_1 | 失败 command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1 | at docker/entrypoint:29
wechat_devtools_1 | at
wechat-web-devtools-linux_wechat_devtools_1 exited with code 1

**Comment by msojocs** [comment]
把tmp也删了；
cache文件夹有没有重新出现？没有见新建cache文件夹。

**Comment by luowa-technology** [comment]
> 把tmp也删了； cache文件夹有没有重新出现？没有见新建cache文件夹。

cache文件夹重新出现。把tmp删掉后运行docker-compose回到了第一次报错的情况：
wechat_devtools_1  | npm WARN deprecated spdlog@0.11.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
wechat_devtools_1  | npm ERR! code 1
wechat_devtools_1  | npm ERR! path /workspace/package.nw/node_modules_tmp/node_modules/native-watchdog
wechat_devtools_1  | npm ERR! command failed
wechat_devtools_1  | npm ERR! command sh -c node-gyp rebuild
wechat_devtools_1  | npm ERR! make: Entering directory '/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog/build'
wechat_devtools_1  | npm ERR!   CXX(target) Release/obj.target/watchdog/src/watchdog.o
wechat_devtools_1  | npm ERR! watchdog.target.mk:111: recipe for target 'Release/obj.target/watchdog/src/watchdog.o' failed
wechat_devtools_1  | npm ERR! make: Leaving directory '/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog/build'
wechat_devtools_1  | npm ERR! gyp info it worked if it ends with ok
wechat_devtools_1  | npm ERR! gyp info using node-gyp@4.0.0
wechat_devtools_1  | npm ERR! gyp info using node@16.4.2 | linux | x64
wechat_devtools_1  | npm ERR! (node:466) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
wechat_devtools_1  | npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
wechat_devtools_1  | npm ERR! gyp info spawn /usr/bin/python2
wechat_devtools_1  | npm ERR! gyp info spawn args [
wechat_devtools_1  | npm ERR! gyp info spawn args   '/workspace/package.nw/node_modules_tmp/node_modules/node-gyp/gyp/gyp_main.py',
wechat_devtools_1  | npm ERR! gyp info spawn args   'binding.gyp',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-f',
wechat_devtools_1  | npm ERR! gyp info spawn args   'make',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-I',
wechat_devtools_1  | npm ERR! gyp info spawn args   '/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog/build/config.gypi',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-I',
wechat_devtools_1  | npm ERR! gyp info spawn args   '/workspace/package.nw/node_modules_tmp/node_modules/node-gyp/addon.gypi',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-I',
wechat_devtools_1  | npm ERR! gyp info spawn args   '/home/user/.node-gyp/16.4.2/include/node/common.gypi',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dvisibility=default',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/user/.node-gyp/16.4.2',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/workspace/package.nw/node_modules_tmp/node_modules/node-gyp',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/user/.node-gyp/16.4.2/<(target_arch)/node.lib',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dmodule_root_dir=/workspace/package.nw/node_modules_tmp/node_modules/native-watchdog',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Dnode_engine=v8',
wechat_devtools_1  | npm ERR! gyp info spawn args   '--depth=.',
wechat_devtools_1  | npm ERR! gyp info spawn args   '--no-parallel',
wechat_devtools_1  | npm ERR! gyp info spawn args   '--generator-output',
wechat_devtools_1  | npm ERR! gyp info spawn args   'build',
wechat_devtools_1  | npm ERR! gyp info spawn args   '-Goutput_dir=.'
wechat_devtools_1  | npm ERR! gyp info spawn args ]
wechat_devtools_1  | npm ERR! gyp info spawn make
wechat_devtools_1  | npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 12 ]
wechat_devtools_1  | npm ERR! In file included from ../src/watchdog.cc:9:0:
wechat_devtools_1  | npm ERR! /home/user/.node-gyp/16.4.2/include/node/uv.h:24:0: error: unterminated #ifndef
wechat_devtools_1  | npm ERR!  #ifndef UV_H
wechat_devtools_1  | npm ERR!  ^
wechat_devtools_1  | npm ERR! In file included from ../src/watchdog.cc:9:0:
wechat_devtools_1  | npm ERR! /home/user/.node-gyp/16.4.2/include/node/uv.h:751:34: error: 'uv_' was not declared in this scope
wechat_devtools_1  | npm ERR!  UV_EXTERN int uv_tty_get_winsize(uv_
wechat_devtools_1  | npm ERR!                                   ^
wechat_devtools_1  | npm ERR! ../src/watchdog.cc:122:40: error: expected '}' at end of input
wechat_devtools_1  | npm ERR!  NAPI_MODULE(NODE_GYP_MODULE_NAME, Init);
wechat_devtools_1  | npm ERR!                                         ^
wechat_devtools_1  | npm ERR! make: *** [Release/obj.target/watchdog/src/watchdog.o] Error 1
wechat_devtools_1  | npm ERR! gyp ERR! build error 
wechat_devtools_1  | npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
wechat_devtools_1  | npm ERR! gyp ERR! stack     at ChildProcess.onExit (/workspace/package.nw/node_modules_tmp/node_modules/node-gyp/lib/build.js:262:23)
wechat_devtools_1  | npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
wechat_devtools_1  | npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
wechat_devtools_1  | npm ERR! gyp ERR! System Linux 6.1.0-15-amd64
wechat_devtools_1  | npm ERR! gyp ERR! command "/workspace/node/bin/node" "/workspace/package.nw/node_modules_tmp/node_modules/.bin/node-gyp" "rebuild"
wechat_devtools_1  | npm ERR! gyp ERR! cwd /workspace/package.nw/node_modules_tmp/node_modules/native-watchdog
wechat_devtools_1  | npm ERR! gyp ERR! node -v v16.4.2
wechat_devtools_1  | npm ERR! gyp ERR! node-gyp -v v4.0.0
wechat_devtools_1  | npm ERR! gyp ERR! not ok
wechat_devtools_1  | 
wechat_devtools_1  | npm ERR! A complete log of this run can be found in:
wechat_devtools_1  | npm ERR!     /workspace/cache/npm/node_cache/_logs/2024-03-20T12_45_56_093Z-debug.log
wechat_devtools_1  |  失败  command: "$root_dir/tools/rebuild-node-modules.sh" "$nwjs_version"
wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:156
wechat_devtools_1  |   at 
wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1  |   at docker/entrypoint:29
wechat_devtools_1  |   at 
wechat-web-devtools-linux_wechat_devtools_1 exited with code 1
。

我简单搜了一下，似乎有一个类似的issue：https://stackoverflow.com/questions/64346457/vs-code-yarn-install-error-command-node-gyp-rebuild-directory-vscod-node-mo

**Comment by msojocs** [comment]
尝试一下这个配置：
```
version: "3"
services:
  wechat_devtools:
    image: jiyecafe/wechat-devtools-build:v3 
    # build:
    #   context: ./docker
    #   dockerfile: Dockerfile
    volumes:
      - .:/workspace
      # - ./cache/.npm:/root/.npm
    environment:
      - ACTION_MODE=${ACTION_MODE:-false}
      # - https_proxy=${https_proxy:-}
      - WINE=${WINE:-false}
      - LOCAL_USER_ID=${DOCKER_UID:-1000}
      - LOCAL_GROUP_ID=${DOCKER_GID:-1000}
      - BUILD_VERSION=${BUILD_VERSION:-v0}
    entrypoint: /workspace/docker/docker-entrypoint
    userns_mode: "host"
```

**Comment by msojocs** [comment]
实在不行建议使用release版本

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/bdc30ea3-74eb-4340-9928-73be2439d244)

**Comment by luowa-technology** [comment]
把# - ./cache/.npm:/root/.npm comment之后问题解决：
echat_devtools_1  | 
wechat_devtools_1  | 2024-03-22 04:04:26 (210 KB/s) - '/workspace/cache/compiler/v0.0.7/wcsc.tmp' saved [1310544/1310544]
wechat_devtools_1  | 
wechat_devtools_1  | fix: wcc,wcsc
wechat_devtools_1  | total 272
wechat_devtools_1  | -rw-r--r-- 1 user user   1223 Mar 20 11:24 README.md
wechat_devtools_1  | -rw-r--r-- 1 user user   2106 Mar 20 11:24 generatemd5.js
wechat_devtools_1  | drwxr-xr-x 2 user user   4096 Mar 20 11:24 nodejs
wechat_devtools_1  | drwxr-xr-x 4 user user   4096 Mar 20 11:24 old
wechat_devtools_1  | -rw-r--r-- 1 user user 242968 Mar 20 11:24 package-lock.json
wechat_devtools_1  | -rw-r--r-- 1 user user    607 Mar 20 11:24 package.json
wechat_devtools_1  | drwxr-xr-x 7 user user   4096 Mar 20 11:24 test
wechat_devtools_1  | drwxr-xr-x 4 user user   4096 Mar 20 11:24 wcc_node
wechat_devtools_1  | drwxr-xr-x 2 user user   4096 Mar 20 11:24 wine
wechat_devtools_1  | 
wechat_devtools_1  | added 271 packages, and audited 272 packages in 39s
wechat_devtools_1  | 
wechat_devtools_1  | 4 vulnerabilities (2 moderate, 1 high, 1 critical)
wechat_devtools_1  | 
wechat_devtools_1  | To address all issues, run:
wechat_devtools_1  |   npm audit fix
wechat_devtools_1  | 
wechat_devtools_1  | Run `npm audit` for details.
wechat_devtools_1  |  成功  微信开发者工具安装完毕wechat-web-devtools-linux_wechat_devtools_1 exited with code 0

/etc/issue的结果是：Debian GNU/Linux 12 \n \l

**Comment by msojocs** [comment]
已解决
