### ISSUE TITLE
debian12系统下， 启用工具后，有三个弹窗提示“Couldn't start client Skyline Style Server",“A request has failed. See the output for more information.”.

### ISSUE THREAD

**Issue by StephenWu5** [msojocs/wechat-web-devtools-linux#107]
debian12系统下， 启用工具后，有三个弹窗提示“Couldn't start client Skyline Style Server",“A request has failed. See the output for more information.”.

![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/32475322/a029087f-5f9a-4147-8476-5d69f805ce50)

**Comment by msojocs** [comment]
duplicate https://github.com/msojocs/wechat-web-devtools-linux/issues/88
