### ISSUE TITLE
中文显示问题

### ISSUE THREAD

**Issue by haomingbai** [msojocs/wechat-web-devtools-linux#110]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：不正常

**问题描述**

打开项目后，不能正确显示中文，在工具的大多数位置，中文只能显示为方框

**问题复现**

1. 打开项目

**期望的效果**

正常显示项目中的中文

**截屏**

![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/35718680/d17c60e0-890e-40a0-8683-17397fbcad1b)
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/35718680/02db2dab-5682-43db-b482-5904248f8352)

**版本信息 (这是必要的):**
 - OS: e.g. Fedora 40
 - Package: master branch, 使用方法0自行构建

**代码片段**

**额外的信息**

**Comment by msojocs** [comment]
https://github.com/msojocs/wechat-web-devtools-linux/issues/92

装字体试试。

**Comment by msojocs** [comment]
https://github.com/msojocs/wechat-web-devtools-linux/discussions/119#discussioncomment-10734988
