### ISSUE TITLE
wxs文件有不兼容的新语法, 开发工具直接崩溃

### ISSUE THREAD

**Issue by yutent** [msojocs/wechat-web-devtools-linux#112]
如题, 不知道能处理么

**Comment by msojocs** [comment]
给我个最简洁的复现demo，不然我也不知道什么情况

**Comment by yutent** [comment]
比如你在 wxs文件中, 用一个 let 声明一个变量, 然后在模板里引入这个wxs文件就可以复现了

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/40c4d9df-5677-46cb-8bae-165085131645)

这个语法windows的程序就不支持

**Comment by yutent** [comment]
可以不支持, 工具别崩就行, 正常的报错可以

**Comment by msojocs** [comment]
已处理
