### ISSUE TITLE
调试器里的MOCK功能无效

### ISSUE THREAD

**Issue by Tarwooz** [msojocs/wechat-web-devtools-linux#113]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/48245709/b4d6fa03-dd73-49f5-b0b1-d8ef4f7b147a)

导入规则和导出规则按钮点击了没有反应，手动添加的MOCK也无效

版本：https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2405020-1/WeChat_Dev_Tools_v1.06.2405020-1_x86_64_linux.tar.gz

**Comment by msojocs** [comment]
已复现。

另外，这个是不是没有删除功能？

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/32912a8e-c831-4469-98e1-9925eaf56c99)

草，右键也不能用

**Comment by Tarwooz** [comment]
> ![image](https://private-user-images.githubusercontent.com/20937135/347818446-32912a8e-c831-4469-98e1-9925eaf56c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NDgwNDgsIm5iZiI6MTcyMDc0Nzc0OCwicGF0aCI6Ii8yMDkzNzEzNS8zNDc4MTg0NDYtMzI5MTJhOGUtYzgzMS00NDY5LTk4ZTEtOTkyNWVhZjU2Yzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAxMjkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljOThmODNjYjhhZjQ0NTg4YTA1ZWU5ZGI2MTJjMDUxZDhkZmUyYjU0YThjNzY2MDI1ZWRlNTQ4M2FlMDhmNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LRCJ4lQPklB4PlDx2_uTLZ-OMd140G0GtS9C9kvz4rY)
> 
> 草，右键也不能用

是的 右键也不能用

**Comment by msojocs** [comment]
已处理

**Comment by Tarwooz** [comment]
> 已处理

哇 牛 谢谢大佬!!
