### ISSUE TITLE
npm构建，无法生成miniprogram_npm文件夹以及构建的结果

### ISSUE THREAD

**Issue by cisordeng** [msojocs/wechat-web-devtools-linux#114]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**

点击npm构建，无法生成miniprogram_npm文件夹以及构建的结果，windows官方开发工具1.06.2405020版本npm构建功能是正常的

**问题复现**

1. 打开项目
2. 进入官方npm文档页面 [点击进入](https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html#%E9%BB%98%E8%AE%A4%E7%9A%84%E6%9E%84%E5%BB%BA-npm-%E6%96%B9%E5%BC%8F)
3. 点击默认的构建 npm 方式官方[demo](https://developers.weixin.qq.com/s/BnRGwumq7riq)代码片段，并在开发工具中打开
4. 点击 工具->构建npm 后就能看到错误。

**期望的效果**
期望npm构建功能能够与官方windows版本表现一致，可以正常使用

**截屏**
官方版本表现正常截图
![wechat_2024-07-18_112312_697](https://github.com/user-attachments/assets/0dba7816-620c-4249-affa-9b19005772f5)

linux版本表现不正常截图
![wechat_2024-07-18_112751_970](https://github.com/user-attachments/assets/7c8831b5-1194-444b-b78a-c36b6bd883e4)

**版本信息 (这是必要的):**
 - OS: e.g. Ubuntu 20.04.6 LTS
 - Package: e.g. [io.github.msojocs.wechat-devtools-linux_1.06.2405020-2_amd64.deb](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2405020-2/io.github.msojocs.wechat-devtools-linux_1.06.2405020-2_amd64.deb)
 - Wine Version: e.g. 7 可选

**代码片段**

https://developers.weixin.qq.com/s/BnRGwumq7riq
**额外的信息**

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/1c616cca-40b7-4d23-9971-ae2e1d407b5e)

没有复现

**Comment by cisordeng** [comment]
刚才删除~/.config/wechat-devtools目录后，重新导入代码片段，我也可以了，但是自定义项目默认目录以后，就还会报上面那个错。
![4517964069](https://github.com/user-attachments/assets/968f65d7-9861-428c-97f3-a8d4996d95e3)

可能是官方也有这个bug了，我再测试一下官方windows的，多谢大佬回复

**Comment by cisordeng** [comment]
确定了，[io.github.msojocs.wechat-devtools-linux_1.06.2405020-2_amd64.deb](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2405020-2/io.github.msojocs.wechat-devtools-linux_1.06.2405020-2_amd64.deb)这个我新建一个目录，设置为项目目录，再导入demo也是可以构建npm的。
那个报错的目录，是我设置了ln -s链接目录作为项目目录，构建时候就会报错，可能不支持链接目录，多谢大佬
