### ISSUE TITLE
模板标签不闭合, IDE会崩掉

### ISSUE THREAD

**Issue by yutent** [msojocs/wechat-web-devtools-linux#115]
如题, 如模板中写一个标签, 如果没闭合, 之前的版本是报错, 现在是崩溃

如 `<input type="text" >`

**Comment by msojocs** [comment]
已复现

**Comment by msojocs** [comment]
![image](https://github.com/user-attachments/assets/27a33a33-0f5f-4c94-9a1d-174ab0bcecec)

已处理，等待新版发布。

**Comment by msojocs** [comment]
新版已发布 https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/v1.06.2405020-3
