### ISSUE TITLE
好像视频播放不了大佬

### ISSUE THREAD

**Issue by liushuai05** [msojocs/wechat-web-devtools-linux#118]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**
我这边采用的v1.06.2405020-3  Appimage包，视频能加载，但是一直无法播放，一直转圈，真机上一切正常

**问题复现**

1. 打开项目
2. 建立一个项目
3. 插入一个video然后添加可播放的mp4地址
4. 编译项目
5. 即可复现

**截屏**
![image](https://github.com/user-attachments/assets/1d4370b8-7d41-4f94-9fb3-ed2a22ed4ddd)
![image](https://github.com/user-attachments/assets/0f04bdb4-c707-423a-b53f-690ddf7a3d89)
![image](https://github.com/user-attachments/assets/ef3af1ae-6d88-4bf8-bfdc-57f8b24eb3a7)

**版本信息 (这是必要的):**
 - OS:  manjaro 24

**代码片段**
[minicode-2.zip](https://github.com/user-attachments/files/17083600/minicode-2.zip)

**Comment by msojocs** [comment]
已复现

**Comment by msojocs** [comment]
已修复

**Comment by liushuai05** [comment]
> 已修复

牛的，不愧是大佬，已确认该问题修复
