### ISSUE TITLE
无法在aarch64设备上正常构建

### ISSUE THREAD

**Issue by ArtemisSaber** [msojocs/wechat-web-devtools-linux#121]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**
Docker构建失败

**问题复现**
$ sudo ./build-with-docker.sh
报错：exec /bin/bash: exec format error
**期望的效果**
正常构建

**截屏**

![Screenshot_20241010_132231](https://github.com/user-attachments/assets/fb126b17-02c0-4a89-937f-2b7aef679322)

**版本信息 (这是必要的):**
 - OS: Asahi Linux Fedora 40

**代码片段**

**额外的信息**
可能是不支持aarch64，能否使用微信官方提供的arm64版本构建aarch64版本linux可用工具？

**Comment by msojocs** [comment]
这个镜像是x86专用的

**Comment by msojocs** [comment]
mac不是有官方支持？

**Comment by ArtemisSaber** [comment]
> mac不是有官方支持？

用的mac装asahi linux……

**Comment by msojocs** [comment]
那我建议你直接用Mac。
