### ISSUE TITLE
[Question] 请问如何禁用某些插件？

### ISSUE THREAD

**Issue by kands-code** [msojocs/wechat-web-devtools-linux#125]
微信的这个开发者工具默认会加载许多插件，但是很多插件实际上不太能用上，例如 Docker 插件，以及无法在 Linux 上使用的 Skyline 插件，但是这些插件在插件面板中没有显示，在设置中也似乎没有暴露出什么方法来禁用，有时候不小心点到就会有一些报错，特别是 Skyline 插件，特别影响使用体验，所以有没有什么方法能够禁用这些插件，比如修改什么配置文件，或者直接删除对应的插件内容什么的。

**Comment by msojocs** [comment]
我研究一下

**Comment by kands-code** [comment]
嗯嗯，谢谢了

**Comment by msojocs** [comment]
`package.nw/js/libs/vseditor/extensions/wechat-miniprogram-development/extension.js`

搜索 `this.skylineStyleClient.init(),` 删除应该就行，明天我加上。

**Comment by msojocs** [comment]
已发布

**Comment by msojocs** [comment]
我先关了
