### ISSUE TITLE
WSL2 AppImage 启动错误

### ISSUE THREAD

**Issue by cqh963852** [msojocs/wechat-web-devtools-linux#126]
**问题描述**

在 WSL2 下，使用 AppImage 时，出现路径错误。`./AppRun: line 5: /bin/wechat-devtools: No such file or directory`

![image](https://github.com/user-attachments/assets/56453c10-82a4-4573-8278-d417b34772c5)

**版本信息 (这是必要的):**
 - OS: WSL2 Ubuntu24.04

**代码片段**

**额外的信息**

![image](https://github.com/user-attachments/assets/a0eadcaa-0040-45d0-a217-46fbf9542401)

![image](https://github.com/user-attachments/assets/d626c975-ac0b-4fde-9420-74a0fc0d242b)

可能与相对路径相关 https://github.com/AppImage/AppImageKit/issues/1035

**Comment by msojocs** [comment]
解直接用bin/wechat启动
