### ISSUE TITLE
bug:模拟器空白

### ISSUE THREAD

**Issue by viger** [msojocs/wechat-web-devtools-linux#17]
问题描述:
载入项目后，模拟器空白，调试器报错:
`[ WXML 文件编译错误] 
/home/xxx/.config/wechat_devtools/WeappVendor/wcc.exe: 1: MZ����@���: not found
/home/xxx/.config/wechat_devtools/WeappVendor/wcc.exe: 2: ��aVK�#��: not found
/home/xxx/.config/wechat_devtools/WeappVendor/wcc.exe: 3: Syntax error: word unexpected
(env: Windows,mp,1.05.2201240; lib: 2.15.0)
[ WXSS 文件编译错误] 
/home/xxx/.config/wechat_devtools/WeappVendor/wcsc.exe: 1: MZ����@���: not found(env: Windows,mp,1.05.2201240; lib: 2.15.0)`
问题呈现:
![Screenshot from 2022-02-26 11-29-31](https://user-images.githubusercontent.com/170866/155827411-90fe5888-c401-4e2b-9e4b-23675b0fe878.png)
系统平台:
Linux Mint 20.2 Cinnamon 5.4.0-92-generic
安装包:
WeChat_Dev_Tools_v0.17_x86_64_wine.tar.gz

**Comment by msojocs** [comment]
我使用该版本未复现问题，
请检查一下`～/.config/wechat_devtools/WeappVendor/wcc.exe`文件是否存在

然后，请尝试删除`～/.config/wechat_devtools`目录

若无效，抱歉由于乱码无法知晓细节，请尝试使用`no_wine`版本

如果您有足够的时间，可以新建默认项目进行测试，
然后，点击`菜单栏-微信开发者工具-调试-调试微信开发者工具`查看是否有与`wcc`相关的报错
或者创建一个能够复现该问题的代码片段

**Comment by viger** [comment]
你好，
确认～/.config/wechat_devtools/WeappVendor/wcc.exe文件存在，尝试删除～/.config/wechat_devtools目录，重启应用后问题依旧存在
打开调试微信开发工具，报如下错误:
![Screenshot from 2022-02-26 12-25-06](https://user-images.githubusercontent.com/170866/155828891-29281205-b033-4193-9e3f-3480b0a99edf.png)
创建基础版本，错误依旧。
谢谢。

**Comment by viger** [comment]
你好，使用none-wine版本正确渲染出来了。
感谢你创建的此项目，以前都是虚拟机+微信开发工具，现在不用那么麻烦了。

**Comment by msojocs** [comment]
截图中的控制台报错属于正常报错，根据控制台信息执行的程序应为`AppImage`可执行文件而不是`tar.gz`解压后的文件，
但是我使用`AppImage`仍然未复现，推测为`wine`执行`wcc.exe`时出现问题。

## 额外请求
由于您开始尝试`none-wine`且通过测试，故此处为额外请求；
如果方便，您可以提供`wine /path/to/wcc.exe`的结果吗？

**Comment by msojocs** [comment]
问题不能复现，根据搜索引擎结果应该跟`wine`有关，似乎安装`wine-binfmt`能解决？不太确定~
