### ISSUE TITLE
Aur包版本号混乱

### ISSUE THREAD

**Issue by maoxuner** [msojocs/wechat-web-devtools-linux#18]
**问题描述**

开发者工具exe文件版本`1.05.2201240`

Aur包版本`1.05.2201242`

为什么两个版本号不一样

**问题复现**
复现问题需要进行的操作:
1. 打开 'PKGBUILD'

**期望的效果**
版本号一致。不同的版本号是有其他意义的吗？

**截屏**
添加截图图片有助于解释您的问题.

**版本信息 (这是必要的):**
 - OS: Arch
 - Package [e.g. xxx_wine.tar.gz]
 - Wine Version [e.g. 7]

**额外的信息**
一些关于此问题的额外信息.

**Comment by msojocs** [comment]
emmm.....
我这版本号卡住了，就跳了几个版本测试，发现好像没什么用～
![image](https://user-images.githubusercontent.com/20937135/155889166-44f8cc35-e5a4-48ce-849d-8d243f35eab2.png)

**Comment by msojocs** [comment]
改回去了～

**Comment by maoxuner** [comment]
已经安装`1.05.2201242-2`版本aur包的小伙伴无法直接“升级”到`1.05.2201240-15`。可以手动构建并安装该软件包。
```bash
cd ~/.cache/yay/wechat-devtools
makepkg
makepkg -i
```
可能通过修改`epoch`能够解决这个问题，但是也不太必要。

**Comment by msojocs** [comment]
> 已经安装`1.05.2201242-2`版本aur包的小伙伴无法直接“升级”到`1.05.2201240-15`。可以手动构建并安装该软件包。
> 
> ```shell
> cd ~/.cache/yay/wechat-devtools
> makepkg
> makepkg -i
> ```
> 
> 可能通过修改`epoch`能够解决这个问题，但是也不太必要。

**Comment by msojocs** [comment]
> 已经安装`1.05.2201242-2`版本aur包的小伙伴无法直接“升级”到`1.05.2201240-15`。可以手动构建并安装该软件包。
> 
> ```shell
> cd ~/.cache/yay/wechat-devtools
> makepkg
> makepkg -i
> ```
> 
> 可能通过修改`epoch`能够解决这个问题，但是也不太必要。

你那边可以在管理器看到新的版本？
卡在9我就怀疑它是不是按字符比较导致`10`小于`9`。
但是看到命令行结果，我觉得我这边可视化的管理器有问题（但是其它软件迭代正常），以后还是用命令行吧。
![image](https://user-images.githubusercontent.com/20937135/155928187-5749eed2-440d-4480-83fd-fe1aaf691f06.png)

**Comment by maoxuner** [comment]
我一直用的命令行，没用管理器。如果真是管理器有问题，你可以把bug反馈上去

**Comment by msojocs** [comment]
> 我一直用的命令行，没用管理器。如果真是管理器有问题，你可以把bug反馈上去

ok, 了解了

**Comment by maoxuner** [comment]
你测试图形界面的软件包版本比较的功能时，可以自建一个本地软件仓库，然后修改本地软件包的版本。
[Local Repository](https://wiki.archlinux.org/title/Pacman/Tips_and_tricks#Custom_local_repository)
