### ISSUE TITLE
AUR PKGUILD 中 compiler的md5sums错误

### ISSUE THREAD

**Issue by archer-n** [msojocs/wechat-web-devtools-linux#20]
**问题描述**
AUR PKGUILD 中 compiler的md5sums错误，导致通过yay  -S wechat-devtools安装失败

**问题复现**
复现问题需要进行的操作:
yay -S wechat-devtools

清除缓存

**期望的效果**
修改 compiler.tar.gz 的md5sums 为 a9e061c97afbbc295b5664a2d8065492  

**截屏**
![image](https://user-images.githubusercontent.com/69684296/155918770-46ba305c-0b62-4e4e-9bca-a3da5977999e.png)

![image](https://user-images.githubusercontent.com/69684296/155918729-7fd98057-de41-4da8-984c-2de81a8c08f8.png)

**版本信息 (这是必要的):**
 - OS: Arch Linux
 - Package: aur

**额外的信息**

**Comment by msojocs** [comment]
感谢，早上手忙脚乱没处理好

**Comment by msojocs** [comment]
处理完毕
