### ISSUE TITLE
 $gwx is not defined

### ISSUE THREAD

**Issue by fg607** [msojocs/wechat-web-devtools-linux#25]
[渲染层错误] ReferenceError: $gwx is not defined
    at http://127.0.0.1:30200/__pageframe__/__dev__/wxappcode.js?t=wechat&s=1646492680744&v=cb124726ca2e1297b97246eb86a68e31:4:30(env: Windows,mp,1.05.2203030; lib: 2.21.2)

**Comment by msojocs** [comment]
请提供版本信息；
以及 helloworld 测试是否正常？

**Comment by fg607** [comment]
@msojocs 最新的v0.24 release版本

**Comment by msojocs** [comment]
> @msojocs 最新的v0.24 release版本

请提供一下完整名称，以及默认项目 helloworld 是否正常？

**Comment by fg607** [comment]
@msojocs  
WeChat_Dev_Tools_1.05.2203030_v0.24_x86_64_no_wine.tar.gz 
编译会出现$gwx is not defined
之前的版本可以用，项目没问题

**Comment by fg607** [comment]
@msojocs 
WeChat_Dev_Tools_1.05.2203030_v0.24_x86_64_wine.tar.gz
这个版本编译找不到同目录下引用的其他文件，例如文件中通过./index.wxs找不到同目录中的index.wxs文件

**Comment by msojocs** [comment]
我暂时没有复现该问题，可以尝试：
1. 删除`~/.config/wechat_devtools` 目录
2. 提供代码片段

**Comment by msojocs** [comment]
没有后续跟进，如有需要请重开 issue 。
