### ISSUE TITLE
使用一段时间后左边模拟器白屏（随机性）

### ISSUE THREAD

**Issue by IvesSSa** [msojocs/wechat-web-devtools-linux#32]
**预先准备**
1. 已经删除`~/.config/wechat_devtools`目录，重新打开项目（问题未能解决）；
2. HelloWorld正常

**问题描述**
在使用一段时间后保存代码自动编译左边模拟器界面会随机性白屏（大概过1～2分钟左右会自动编译成功），只能看见底部导航栏，f12控制台也没有相关报错信息

**问题复现**
写项目时随机性发生

**截屏**
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/45648391/158929527-7f01bc2a-09dd-4bb0-b56e-91eb67aa947f.png">

**版本信息 (这是必要的):**
 - OS: Manjaro 
 - Package: AUR版本 wechat-devtools 2:1.05.2203070-3
 - Wine Version: 用的node版本编译（14.18.3）

**Comment by msojocs** [comment]
概率性问题，暂未复现
> 大概过1～2分钟左右会自动编译成功

这是什么意思？

----

## 环境信息（仅做记录）
1. devtools版本1.05.2203070
2. lib: 2.23.0
3. 懒加载：关
4. 热重载：关
5. wine: false
6. uniapp？

**Comment by IvesSSa** [comment]
> 概率性问题，暂未复现
> 
> > 大概过1～2分钟左右会自动编译成功
> 
> 这是什么意思？
> 
> ## 环境信息（仅做记录）
> 1. devtools版本1.05.2203070
> 2. lib: 2.23.0
> 3. 懒加载：关
> 4. 热重载：关
> 5. wine: false
> 6. uniapp

就是白屏之后经过1～2分钟又自己好了，我换了AppImage版本 暂未发现问题

**Comment by msojocs** [comment]
wxid_4jtnthlm6amf22

**Comment by IvesSSa** [comment]
搜索不到您。。 我的是168192930 麻烦大佬加一下

**Comment by sdlddr** [comment]
大佬 ，最近官方更新了新版本1.06.2204180，我看这里面修复的那一长串问题列表，有些好像就是我前段时间跟您一直反馈说没解决反复出现的。

**Comment by msojocs** [comment]
不排除 官方版本在Linux下的兼容存在不友好的可能，如有确定的复现步骤请创建新的 issue 。
