### ISSUE TITLE
Ubuntu 16.04 模拟器正常显示，调试器不显示

### ISSUE THREAD

**Issue by LZHD** [msojocs/wechat-web-devtools-linux#33]
**预先准备**
1. 删除`~/.config/wechat_devtools`目录，重新打开项目（若发布`issue`即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：模拟器正常显示，调试器不显示

**问题描述**
1. 初次打开开发者工具，提示“无法加载以下来源的扩展程序： . 清单文件缺失或不可读取”
2. 导入小程序，模拟器可以正常显示，调试器显示不出来（调试基础库一直在加载中）

**问题复现**
复现问题需要进行的操作:
1. 打开项目
3. 点击 '切换调试器'
4. 调试器始终不显示

**期望的效果**
可以正常显示调试器

**截屏**
![选区_177](https://user-images.githubusercontent.com/9976942/159230168-023702fe-f1d9-4969-96b5-69e2a36b93e5.png)

![miniprogram-1 - 微信开发者工具 Stable v1 05 2203070_178](https://user-images.githubusercontent.com/9976942/159231251-6fd88920-4461-4d21-ae32-0692d9b5e488.png)

**版本信息 (这是必要的):**
 - OS: e.g. Ubuntu 16.04 xenial
 - Package: e.g. WeChat_Dev_Tools_v1.05.2203070-6_x86_64_no_wine.AppImage
 - Wine Version: e.g. 7 可选

**代码片段**
提供代码片段对维护者定位与修复问题有极大帮助；
若阁下不能提供，且维护者不能复现问题，那么阁下的`issue`将被搁置或者关闭。
[查看创建代码片段的教程](https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html)

**额外的信息**
一些关于此问题的额外信息。

**Comment by msojocs** [comment]
请执行`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC`；
然后，回复执行结果

**Comment by msojocs** [comment]
若不存在`GLIBCXX_3.4.22`
请执行
```bash
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
```

**Comment by msojocs** [comment]
我在本地完成的ubuntu16.04的兼容，明天整理一下提交。
你急的话先用上面方法试试。

**Comment by LZHD** [comment]
> 请执行`strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC`； 然后，回复执行结果

![选区_179](https://user-images.githubusercontent.com/9976942/159389737-41fdc33a-c844-42ff-a1e9-049464cdf941.png)

**Comment by LZHD** [comment]
> 若不存在`GLIBCXX_3.4.22` 请执行
> 
> ```shell
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test
> sudo apt-get update
> sudo apt-get install gcc-4.9
> sudo apt-get upgrade libstdc++6
> ```

按这个办法试了一下，调试器可以出来了，谢谢啦

**Comment by msojocs** [comment]
新版兼容 Ubuntu16.04
已发布：https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/v1.05.2203070-7
