### ISSUE TITLE
关于浅色暗色主题跟随系统的功能

### ISSUE THREAD

**Issue by icepie** [msojocs/wechat-web-devtools-linux#35]
感觉这也不算个bug, 就当是个requests吧...不要太在意! 

折腾了半天没定位到它是怎么监听系统主题变化的....如果可以的话, 希望能支持一下linux下gtk亮暗色主题变化的监听

在 `vscode` 我一般用的是这个插件 [vscode-auto-dark-mode-windows](https://github.com/danielgjackson/vscode-auto-dark-mode-windows) 但是能力有限没看懂他是咋监听的...希望能给大家提供点帮助

**Comment by msojocs** [comment]
基于chromium的浏览器似乎都存在此问题（Linux不兼容）
测试了一下Edge [ Version 100.0.1185.29 (Official build) (64-bit) ]，同样不支持亮暗色识别（默认总是亮的）

https://bugs.chromium.org/p/chromium/issues/detail?id=998903
相关代码：
`window.matchMedia("(prefers-color-scheme)")`
`window.matchMedia("(prefers-color-scheme:dark)")`
`window.matchMedia("(prefers-color-scheme:light)")`

可能的处理方案
---
虽然目前浏览器不支持，但可以间接实现。
执行如`gsettings get org.gnome.desktop.interface gtk-theme`这样的命令来获取主题的亮暗。
使用上方代码指令替换`(prefers-color-scheme)`相关的查询语句，这样可以实现目的；
但是，这个实现比较复杂，因为Linux的桌面不是只有一个；
有`dde`、`gnome`、`kde`等，这些桌面的查询方式都不一样。

结论
---
暂不处理

**Comment by msojocs** [comment]
https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/continuous

**Comment by msojocs** [comment]
请尝试最新的continuous版本是否符合预期

**Comment by icepie** [comment]
辛苦了，一会就测

**Comment by icepie** [comment]
貌似重新构建后在gnome不起作用

**Comment by icepie** [comment]
已找到问题所在, 在 `gnome` 下很多第三方GTK主题都是以 `Dark` 结尾标明暗色的, 由于我使用了 `Flat-Remix-Theme` 所以会导致没能切换....这个处理起来相对容易

另外在 `gnome42` 的环境下, 已经官方支持了亮暗色主题...可以通过

```bash
 $ gsettings get org.gnome.desktop.interface color-scheme
```

判断该值是否为 `prefer-dark` 来更准确的判断是否处于暗色模式!

**Comment by msojocs** [comment]
感谢提交PR
新的continuous版本已完成构建

**Comment by icepie** [comment]
感谢, 经测试 continuous 版本主题跟随系统已可用!

但是在aur的构建脚本当中, `nwjs` 和 `nodejs` 版本, 还未得到更新...

**Comment by msojocs** [comment]
好的，感谢测试
aur脚本会进行跟进的。
