### ISSUE TITLE
AUR升级nwjs遇到undefined symbol问题

### ISSUE THREAD

**Issue by msojocs** [msojocs/wechat-web-devtools-linux#37]
目前 master 分支nwjs版本0.55.0，AUR需要跟进更新。

AUR进行脚本更新后，编译使用正常；
AUR尝试将版本替换为0.55.0(node16.4.2)后，编译运行主界面右侧无法显示，工具调试器报spdlog相关报错`undefined symbol: xxxx`；
使用nw-gyp重新构建spdlog，主界面正常显示，但是出现扩展宿主意外终止的报错。

**Comment by icepie** [comment]
直接使用 actions 当中 `build-src` 中的 `no-wine` 构建的 `Continuous` 版本在 `archlinux` 上无问题...猜测是AUR构建时某些依赖太新?

**Comment by msojocs** [comment]
@icepie 
makepkg命令的构建环境似乎和宿主不一致。
我在宿主环境直接进行构建，没有问题；
但是使用makepkg构建后，显示spdlog模块有问题。
而我用宿主构建生成的spdlog.node替换makepkg生成的spdlog.node后，程序执行正常。
两种方式构建生成的spdlog.node大小差了5kb左右。

**Comment by msojocs** [comment]
在使用`spdlog`关键字查找代码时，发现这个`s="object"==typeof nw?require("spdlog"):require("spdlog-node")`
初步猜测，`spdlog`使用`node-gyp`构建，`spdlog-node`使用`node-gyp`构建；
经验证，确实如此，两个分开构建后一切正常（之前都是默认使用`node-gyp`构建）

**Comment by icepie** [comment]
看样子貌似找到了问题所在, 辛苦了 @msojocs !

另外在aur里可否添加一下 `wechat-devtools-cli` 的支持.

我建议使用这样的目录结构: 

```
/opt/wechat-devtools/bin
├── wechat-devtools
└── wechat-devtools-cli

/usr/bin
├── wechat-devtools (软链)
└── wechat-devtools-cli (软链)
```

`.desktop` 里直接运行 `wechat-devtools` 即可

**Comment by msojocs** [comment]
@icepie 
好的，感谢建议，会加上的
deb应该也要做一样的支持，到时候统一处理。
