### ISSUE TITLE
预览时无法显示模板, 提示 Template `xxx` not found.

### ISSUE THREAD

**Issue by icepie** [msojocs/wechat-web-devtools-linux#42]
**问题描述**
在 `wxml` 使用 `template` 时, 调试器会报 `Template "xxx" not found.` 并无法显示这个模板

而真机调试却可以直接显示它 (可以排除是编译的问题)

**问题复现**
复现问题需要进行的操作:
根据 [文档](https://developers.weixin.qq.com/miniprogram/dev/reference/wxml/template.html) 创建一个新项目, 并使用 `template`

**期望的效果**
在小程序开发工具当中正常显示 `template`

**截屏**
待添加

**版本信息 (这是必要的):**
 - OS: ArchLinux
 - Package: [wechat-devtools-2-1.05.2203070-10-x86_64.pkg.tar.zst](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.05.2203070-10/wechat-devtools-2-1.05.2203070-10-x86_64.pkg.tar.zst)

**代码片段**
```
<!-- 定义template -->
<template name="msgItem">
  <view>
    <text> {{index}}: {{msg}} </text>
    <text> Time: {{time}} </text>
  </view>
</template>


<!-- 使用 template -->
template is="msgItem" data="{{...item}}"/>

```

**额外的信息**
一些关于此问题的额外信息。

**Comment by icepie** [comment]
稍等...貌似是项目的问题...新建的项目没复现 ...

**Comment by icepie** [comment]
找到了..刚刚新建的是ts模板这个没问题, 但是js模板就不能预览这个组件了

**Comment by icepie** [comment]
问题貌似解决了? 
因为 `ts` 的模板默认关闭了懒加载...

然后我把 `js` 的 `app.json` 去掉以下行
```json
"lazyCodeLoading": "requiredComponents"
```

就可以正常显示 `template` 了

**Comment by msojocs** [comment]
懒加载是我自己实现的所以会有兼容性问题，待处理。

**Comment by msojocs** [comment]
支持template的`continuous`版本已发布，请测试。

**Comment by icepie** [comment]
开启懒加载后会出现以下问题

```
[渲染层错误] TypeError: Cannot set property 'xxx' of undefined
```
待我清除一下数据再测试


> 支持template的`continuous`版本已发布，请测试。
> 
> https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/continuous

**Comment by icepie** [comment]
清除缓存后问题和起初描述的一致

确认是刚下的 `continuous` 版本

```
local/wechat-devtools 2:1.05.2204180-0
    WeChat Devtools For Linux.
```

**Comment by msojocs** [comment]
可能原因：
1. 不支持你的项目代码编写的情况
2. aur打包时出了问题

我用构建的AppImage测试简单修改后的默认项目是可以的
![image](https://user-images.githubusercontent.com/20937135/164956194-078dd06b-b482-4676-bc60-f68a7605b112.png)

**Comment by icepie** [comment]
奇怪了, 我下载一下打包出来的 `src` 试一下

![图片](https://user-images.githubusercontent.com/28620142/164956296-6e8c9bc2-920e-4ce1-bf02-6dd556250c53.png)

**Comment by msojocs** [comment]
我这边`pkg.tar.zst`测试可用，
你看一下`~/.config/wechat-devtools/WeappVendor/wcc`文件md5是不是`71241b1ff80c577134ad0bf8fb3cb682`

**Comment by icepie** [comment]
```bash
$ md5sum ~/.config/wechat-devtools/WeappVendor/wcc
71241b1ff80c577134ad0bf8fb3cb682  /home/icepie/.config/wechat-devtools/WeappVendor/wcc
```

你开启懒加载了么

**Comment by msojocs** [comment]
开了的，怪了

**Comment by icepie** [comment]
我先去吃个午饭, 下午再帮忙看看啥原因 :(

**Comment by huyanyou** [comment]
![image](https://user-images.githubusercontent.com/85886567/164965802-bfe989eb-ad2d-441f-b966-1da026c20c42.png)

用朋友的环境测试了一下(顺便借用一下他的github帐号, 本条还是 @icepie 的发言)

貌似在另一台arch上确实没有问题了...等我回宿舍再具体测试一下, 不过貌似在kde会有app图标未正常加载的问题(可能也是系统的小bug等我重启一下)

**Comment by icepie** [comment]
问题应该解决了，感谢修复！
