### ISSUE TITLE
compose 执行失败

### ISSUE THREAD

**Issue by davidwang2007** [msojocs/wechat-web-devtools-linux#55]
wechat_devtools_1  | Rebuilding wechat-devtools node modules Result Code: 0
wechat_devtools_1  | Patching wechat-devtools
wechat_devtools_1  | Patching Other
wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node': No such file or directory
wechat_devtools_1  | 异常 Error: Command failed: /workspace/tools/fix-other.sh
wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node': No such file or directory
wechat_devtools_1  | 
wechat_devtools_1  |     at checkExecSyncError (node:child_process:826:11)
wechat_devtools_1  |     at execSync (node:child_process:900:15)
wechat_devtools_1  |     at /workspace/tools/update-wechat-devtools-node:319:9
wechat_devtools_1  |     at new Promise (<anonymous>)
wechat_devtools_1  |     at patch_other (/workspace/tools/update-wechat-devtools-node:318:12)
wechat_devtools_1  |     at start (/workspace/tools/update-wechat-devtools-node:337:15)
wechat_devtools_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
wechat_devtools_1  |   status: 1,
wechat_devtools_1  |   signal: null,
wechat_devtools_1  |   output: [
wechat_devtools_1  |     null,
wechat_devtools_1  |     <Buffer 66 69 78 3a 20 77 65 62 76 69 65 77 20 6d 61 6e 61 67 65 72 0a 66 69 78 3a 20 77 63 63 2c 77 63 73 63 0a 74 6f 74 61 6c 20 30 0a>,
wechat_devtools_1  |     <Buffer 63 70 3a 20 63 61 6e 6e 6f 74 20 73 74 61 74 20 27 2f 77 6f 72 6b 73 70 61 63 65 2f 63 6f 6d 70 69 6c 65 72 2f 77 63 63 5f 6e 6f 64 65 27 3a 20 4e 6f ... 24 more bytes>
wechat_devtools_1  |   ],
wechat_devtools_1  |   pid: 13322,
wechat_devtools_1  |   stdout: <Buffer 66 69 78 3a 20 77 65 62 76 69 65 77 20 6d 61 6e 61 67 65 72 0a 66 69 78 3a 20 77 63 63 2c 77 63 73 63 0a 74 6f 74 61 6c 20 30 0a>,
wechat_devtools_1  |   stderr: <Buffer 63 70 3a 20 63 61 6e 6e 6f 74 20 73 74 61 74 20 27 2f 77 6f 72 6b 73 70 61 63 65 2f 63 6f 6d 70 69 6c 65 72 2f 77 63 63 5f 6e 6f 64 65 27 3a 20 4e 6f ... 24 more bytes>
wechat_devtools_1  | }
wechat_devtools_1  |  失败  command: node
wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:1
wechat_devtools_1  |   at 
wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1  |   at docker/entrypoint:1
wechat_devtools_1  |   at

**Comment by msojocs** [comment]
文档未更新。

需要拉取子模块： 
1. 在已克隆文件夹下执行 `git submodule update --init --recursive`
2. 重新克隆 `git clone --recurse-submodules https://github.com/msojocs/wechat-web-devtools-linux.git`

**Comment by msojocs** [comment]
文档已跟进

**Comment by shadowfish07** [comment]
@msojocs hello，似乎又出现了一样的问题：
```
 Rebuilding wechat-devtools node modules Result Code: 0
wechat_devtools_1  | Patching wechat-devtools
wechat_devtools_1  | Patching Other
wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory
wechat_devtools_1  | 异常 Error: Command failed: /workspace/tools/fix-other.sh
wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory
wechat_devtools_1  | 
wechat_devtools_1  |     at checkExecSyncError (node:child_process:826:11)
wechat_devtools_1  |     at execSync (node:child_process:900:15)
wechat_devtools_1  |     at /workspace/tools/update-wechat-devtools-node:319:9
wechat_devtools_1  |     at new Promise (<anonymous>)
wechat_devtools_1  |     at patch_other (/workspace/tools/update-wechat-devtools-node:318:12)
wechat_devtools_1  |     at start (/workspace/tools/update-wechat-devtools-node:337:15)
wechat_devtools_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
wechat_devtools_1  |   status: 1,
wechat_devtools_1  |   signal: null,
wechat_devtools_1  |   output: [
wechat_devtools_1  |     null,
wechat_devtools_1  |     <Buffer 66 69 78 3a 20 77 65 62 76 69 65 77 20 6d 61 6e 61 67 65 72 0a 66 69 78 3a 20 77 63 63 2c 77 63 73 63 0a 74 6f 74 61 6c 20 34 38 0a 2d 72 77 2d 72 77 ... 513 more bytes>,
wechat_devtools_1  |     <Buffer 63 70 3a 20 63 61 6e 6e 6f 74 20 73 74 61 74 20 27 2f 77 6f 72 6b 73 70 61 63 65 2f 63 6f 6d 70 69 6c 65 72 2f 77 63 63 5f 6e 6f 64 65 2f 62 69 6e 27 ... 28 more bytes>
wechat_devtools_1  |   ],
wechat_devtools_1  |   pid: 13331,
wechat_devtools_1  |   stdout: <Buffer 66 69 78 3a 20 77 65 62 76 69 65 77 20 6d 61 6e 61 67 65 72 0a 66 69 78 3a 20 77 63 63 2c 77 63 73 63 0a 74 6f 74 61 6c 20 34 38 0a 2d 72 77 2d 72 77 ... 513 more bytes>,
wechat_devtools_1  |   stderr: <Buffer 63 70 3a 20 63 61 6e 6e 6f 74 20 73 74 61 74 20 27 2f 77 6f 72 6b 73 70 61 63 65 2f 63 6f 6d 70 69 6c 65 72 2f 77 63 63 5f 6e 6f 64 65 2f 62 69 6e 27 ... 28 more bytes>
wechat_devtools_1  | }
wechat_devtools_1  |  失败  command: node
wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:1
wechat_devtools_1  |   at 
wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1  |   at docker/entrypoint:1
wechat_devtools_1  |   at 
wechat-web-devtools-linux_wechat_devtools_1 exited with code 255
```
我的执行步骤：
```
git clone --recurse-submodules https://github.com/msojocs/wechat-web-devtools-linux.git
docker-compose up
# 发现出这个问题后来找到了这个issue，执行
git submodule update --init --recursive
# 再次运行docker-compose up 报错依旧
```

**Comment by Nutr1t07** [comment]
我也遇到了同样的问题，

> 文档未更新。
> 
> 需要拉取子模块：
> 
>     1. 在已克隆文件夹下执行 `git submodule update --init --recursive`
> 
>     2. 重新克隆 `git clone --recurse-submodules https://github.com/msojocs/wechat-web-devtools-linux.git`

上述方法无效
