### ISSUE TITLE
编辑器内输入法退格问题

### ISSUE THREAD

**Issue by Rurikou** [msojocs/wechat-web-devtools-linux#56]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常

**问题描述**

输入法打错字退格时会删除之前已经打好的字
**问题复现**

根据截屏图片即可复现
**期望的效果**

 退格只删除输入错误的部分，而不是删除已经打好的部分
**截屏**

![re](https://user-images.githubusercontent.com/23163316/170494111-3248d197-09fa-4359-abbe-00a6f71e7be1.gif)

**版本信息 (这是必要的):**
 - OS: deepin 20.5
 - Package: [io.github.msojocs.wechat-devtools-no-wine_1.05.2204250-2_amd64.deb] 
                    [WeChat_Dev_Tools_v1.05.2204250-2_x86_64_no_wine.AppImage]
 - Wine Version: 无

**代码片段**

无
**额外的信息**

其他IDE正常，（idea系列、vscode均正常）

**Comment by squallliu** [comment]
fcitx5 无此问题

**Comment by Rurikou** [comment]
暂时使用了deepin商店1.05.2201240版本，无此问题。
