### ISSUE TITLE
ubuntu22.04出现导入卡住的问题

### ISSUE THREAD

**Issue by 2715851270** [msojocs/wechat-web-devtools-linux#59]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常

**问题描述**

在ubuntu22.04 下， 导入项目时会卡住， 并一直停留在卡住的层面

**问题复现**

1. 打开项目
2. 点击 导入
3. 就卡住了， 导入个空文件夹都会被卡住。 
4. 然后就没有然后了。 我是直接使用ubuntu22.04 新装系统，不是从18升级过来的系统。下载别的版本也不行

ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
在命令行窗口出现这种错误

**期望的效果**

**截屏**

**版本信息 (这是必要的):**
 - OS: e.g. manjaro
 - Package: [WeChat_Dev_Tools_v1.06.2206020-1_x86_64_no_wine.AppImage](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2206020-1/WeChat_Dev_Tools_v1.06.2206020-1_x86_64_no_wine.AppImage)
 - Wine Version: e.g. 7 可选

**代码片段**

**额外的信息**

**Comment by msojocs** [comment]
希望能有图

**Comment by 2715851270** [comment]
我换回了20.04版本的ubuntu， 然后就好了。
