### ISSUE TITLE
安装过程报错

### ISSUE THREAD

**Issue by yil3** [msojocs/wechat-web-devtools-linux#60]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，
2. 正常

**问题描述**
按照README上的流程安装，出现错误

![2022-07-06 17-14-07 的屏幕截图](https://user-images.githubusercontent.com/57053484/177516093-7c03d525-9c7d-40bf-a3a2-32f71686e30a.png)

**Comment by msojocs** [comment]
请确认 `compiler` 目录下是否有文件

**Comment by yil3** [comment]
![2022-07-06 17-43-06 的屏幕截图](https://user-images.githubusercontent.com/57053484/177521763-ff7745e1-c7e2-4121-a224-51daecdc660c.png)

**Comment by msojocs** [comment]
在 `compiler` 目录下执行 `npm install`；
然后构建，应该就可以了。

**Comment by yil3** [comment]
@msojocs 
cli工具好像会报错了呀

![2022-07-07 12-04-30 的屏幕截图](https://user-images.githubusercontent.com/57053484/177688265-cc896766-60b7-4f53-998e-4dd6678b9dd9.png)

**Comment by yil3** [comment]
成功搞定了

**Comment by yil3** [comment]
准备更新一下程序，又遇到了同样的问题，这次compiler文件夹下没有产生文件

**Comment by yil3** [comment]
@msojocs 
大佬。刚刚更新了最新版本。打开后报错，并且程序完全无法关闭，这是什么原因呀
x-special/nautilus-clipboard
copy
file:///home/x/Pictures/2022-08-17%2010-57-20%20%E7%9A%84%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE.png

**Comment by msojocs** [comment]
没有复现此问题

**Comment by msojocs** [comment]
无响应

**Comment by yil3** [comment]
### 更新最新版本，按照推荐0失败

---
#### log日志
wechat-web-devtools-linux-wechat_devtools-1  |  ######## 版本信息 2022-09-14 07:32:49 ########
wechat-web-devtools-linux-wechat_devtools-1  | NW VERSION: 0.55.0
wechat-web-devtools-linux-wechat_devtools-1  | nw-gyp version: v3.6.6
wechat-web-devtools-linux-wechat_devtools-1  | node version: v16.4.2
wechat-web-devtools-linux-wechat_devtools-1  | npm version: 8.19.2
wechat-web-devtools-linux-wechat_devtools-1  | Python 2.7.12
wechat-web-devtools-linux-wechat_devtools-1  | Python 3.6.5
wechat-web-devtools-linux-wechat_devtools-1  | --2022-09-14 07:32:49--  https://github.com/microsoft/ripgrep-prebuilt/releases/download/v12.1.1-1/ripgrep-v12.1.1-1-x86_64-unknown-linux-musl.tar.gz
wechat-web-devtools-linux-wechat_devtools-1  | Resolving github.com (github.com)... 20.205.243.166
wechat-web-devtools-linux-wechat_devtools-1  | Connecting to github.com (github.com)|20.205.243.166|:443... connected.
wechat-web-devtools-linux-wechat_devtools-1  | Unable to establish SSL connection.
wechat-web-devtools-linux-wechat_devtools-1  | Rebuilding wechat-devtools node modules Result Code: 4
wechat-web-devtools-linux-wechat_devtools-1  | 异常 4
wechat-web-devtools-linux-wechat_devtools-1  |  失败  command: node "$root_dir/tools/update-wechat-devtools-node" $TARGET_VERSION $@
wechat-web-devtools-linux-wechat_devtools-1  |   at ./tools/setup-wechat-devtools-bash:98
wechat-web-devtools-linux-wechat_devtools-1  |   at
wechat-web-devtools-linux-wechat_devtools-1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat-web-devtools-linux-wechat_devtools-1  |   at docker/entrypoint:1
wechat-web-devtools-linux-wechat_devtools-1  |   at
wechat-web-devtools-linux-wechat_devtools-1 exited with code 255
