### ISSUE TITLE
讨论：有没有可能把内置的Git管理器单独提取出来？或者有特别好的替代品

### ISSUE THREAD

**Issue by pawmaster** [msojocs/wechat-web-devtools-linux#61]
一直使用linux环境，但是没遇到一个趁手的git管理器。

- 一些出名的，比如`gitkraken`，感觉凑合能用。
- 还有smartgit，交互设计都很老，不太好用
- 最好用的应该是`sourcetree`，只是没有linux平台的

开发者工具内置了一个Git管理器，我觉得挺好用的，跟sourcetree很像，就是无法单独在任意项目中使用。所以在想，有没有这个可能提取出来？

**Comment by msojocs** [comment]
提取生产环境代码，不现实。

**Comment by ystyle** [comment]
我个人觉得最好用的git界面管理器应该是jetbrain ide自带那个
