### ISSUE TITLE
通过 Snap 安装后无法启动

### ISSUE THREAD

**Issue by lomirus** [msojocs/wechat-web-devtools-linux#63]
**问题描述**
通过 Snap 安装后 wechat-devtools 后，无法在终端通过 `wechat-devtools` 启动，且 Launcher 也没有出现相关启动图标

**问题复现**
```bash
$ snap install wechat-devtools
snap "wechat-devtools" is already installed, see 'snap help refresh'
$ wechat-devtools
zsh: command not found: wechat-devtools
```

**期望的效果**
能够启动程序

**截屏**
![](https://i.imgur.com/9nJs0kB.png)

**版本信息 (这是必要的):**
 - OS: Manjaro
 - Package: 1.06.2206020-1
 - Wine Version: 7.13

**Comment by msojocs** [comment]
缺少维护，不建议使用snap。
