### ISSUE TITLE
根据文档推荐的方法0安装失败

### ISSUE THREAD

**Issue by lee-stars** [msojocs/wechat-web-devtools-linux#65]
**问题描述**
安装失败

**问题复现 据 - 方法0（推荐）**
方法0（推荐）

理论上此方法99%成功;在网络不稳定时容易失败（原因懂得都懂，构建过程已经尽量使用镜像源）

    如果构建 wine 版本，请先在Linux环境中自行安装 wine wine-binfmt；
    请安装 docker docker-compose
    克隆本项目：

    git clone --recurse-submodules https://github.com/msojocs/wechat-web-devtools-linux.git

    在本地项目目录中执行如下的语句，构筑开发者工具：

    docker-compose up

    在本地项目目录中执行如下的语句，可以安装应用图标（非必须）：

    ./tools/install-desktop-icon-node

之后即可通过点击应用图标启动微信开发者工具，也可以运行 bin/wechat-devtools 通过命令行启动

**期望的效果**
最起码安装成功呀。

**截屏**
![2022-08-27 03-54-40屏幕截图](https://user-images.githubusercontent.com/111681930/186982074-0c12eba1-b037-4747-9ddc-f0c379bca869.png)

**版本信息**
 - OS: Linux Mint 21 Cinnamon

**Comment by msojocs** [comment]
截图缺少关键信息，无法确定原因。

**Comment by msojocs** [comment]
无响应
