### ISSUE TITLE
自动更新窗口无法关闭

### ISSUE THREAD

**Issue by ChenSino** [msojocs/wechat-web-devtools-linux#66]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常

**问题描述**
今天启动工具，收到推送更新窗口，窗口无法关闭掉，只能`kill`

**问题复现**
1. 收到推送更新时会自动复现；
2. 手动点击检查更新也能复现；

**期望的效果**
希望屏蔽工具自动更新或者能够关闭自动弹出的窗口

**截屏**
![image](https://user-images.githubusercontent.com/25560521/187024399-39d8393f-cee7-4ec9-b309-3d316c76f364.png)

**版本信息 (这是必要的):**
 - OS:  Manjaro 21.3.7 Ruah
 - Package: 通过` yay -S wechat-devtools`安装的

**代码片段**

**额外的信息**

**Comment by ChenSino** [comment]
杀死进程后，重新打开过一会会自动弹出更新

**Comment by msojocs** [comment]
已复现该问题

**Comment by icepie** [comment]
如果是gnome的话, alt + 空格可以把这个窗口关闭

**Comment by msojocs** [comment]
已发布新版本

**Comment by ChenSino** [comment]
> 已发布新版本
测试ok，新版可以正常关闭，我更新后的版本为1.06.2207210-1。
 `aur/wechat-devtools 2:1.06.2207210-1 (+21 1.10) (已安装)`
