### ISSUE TITLE
跑起来的项目全部为Iframe标签，无法选中Dom

### ISSUE THREAD

**Issue by zhangpeichao-cmd** [msojocs/wechat-web-devtools-linux#68]
**问题描述**
跑起来的项目全部为Iframe标签，无法选中Dom

**问题复现**
1. 打开项目
2. 点击任意页面
3. 看到问题

**期望的效果**

正常的文档流，能够选中dom，能够查看元素的样式等信息

**截屏**
![image](https://user-images.githubusercontent.com/81732513/189263268-e1e5d04d-b7ec-436d-8ef8-d7f3ede54aad.png)

**版本信息 (这是必要的):**
 - OS: e.g. ubuntu20.04
 - Package: e.g. [WeChat_Dev_Tools_v1.06.2208010-1_x86_64_linux.tar.gz](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2208010-1/WeChat_Dev_Tools_v1.06.2208010-1_x86_64_linux.tar.gz)

**代码片段**

**Comment by msojocs** [comment]
问题：调试器没有正常加载

**Comment by zhangpeichao-cmd** [comment]
> 问题：调试器没有正常加载

你好，我试了很多次都是iframe标签 我应该怎么做才能显示正常的文档流呢

**Comment by zhangpeichao-cmd** [comment]
> 问题：调试器没有正常加载

页面也是正常显示  点击事件也都ok 除了iframe无法选中元素查看元素以外其他的都好着

**Comment by msojocs** [comment]
过于久远，关闭
