### ISSUE TITLE
Linux 下运行报错, 导入新项目卡住动不了, 新建项目没问题.

### ISSUE THREAD

**Issue by luciddream-tsin** [msojocs/wechat-web-devtools-linux#69]
```shell
(base) tsin@luciddream:~/下载$ ./WeChat_Dev_Tools_v1.06.2208010-1_x86_64_linux.AppImage 
Error: unrecognized flag --harmony-weak-refs
Try --help for options
[34280:34285:0909/144448.289821:ERROR:cert_verify_proc_builtin.cc(601)] No net_fetcher for performing AIA chasing.
Error: unrecognized flag --harmony-weak-refs

```

**Comment by onhao** [comment]
一样的问题，无法导入项目：
Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': A version change transaction is running.
    at /home/opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/core.wxvpkg/4c14765e209054f84dc0f5467b913a38.js:2:638
    at new Promise (<anonymous>)
    at Proxy.insert (/home/opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/core.wxvpkg/4c14765e209054f84dc0f5467b913a38.js:2:608)
    at Proxy.insert (/home/opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/core.wxvpkg/48794d87a1eae5ac17a15799db2db01c.js:2:399)
    at /home/opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/core.wxvpkg/dba45d35e216ac358749348350f791e7.js:2:3887





Unchecked runtime.lastError: {"code":-32601,"message":"'Emulation.setSafeAreaInset' wasn't found"}





Failed to load resource: the server responded with a status of 429 ()




/home/opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/node_modules.wxvpkg/@sentry/utils/dist/instrument.js:1 [2022-09-14 07:37:31.644] [ERROR] [/home/opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/core.wxvpkg/e90b7cb007787228bc8fe5535731b603.js] writeFileSync fail to get lock /home/wuhao/.config/wechat-devtools/WeappLocalData/localstorage_b72da75d79277d2f5f9c30c9177be57e.json

**Comment by 2715851270** [comment]
最新版的在ubuntu20.04 下， 启动后一闪而过， 就没有然后了。  2208010-1 就没有这个问题。  linux版本， 非wine版

**Comment by msojocs** [comment]
过于久远，关闭
