### ISSUE TITLE
导入Taro编写的小程序无法编译成功，白屏。

### ISSUE THREAD

**Issue by smoothdvd** [msojocs/wechat-web-devtools-linux#70]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常

**问题描述**

导入Taro编写的小程序无法编译成功，白屏。

**问题复现**

1. 导入Taro buid:weapp生成的dist目录
2. 看到问题
```
[ WXML 文件编译错误] 
ENOENT: no such file or directory, stat '/opt/wechat-devtools/nwjs/package.nw/node_modules/wcc-exec'
(env: Linux,mp,1.06.2209070; lib: 2.26.1)
```

**期望的效果**

能正确导入

**截屏**

**版本信息 (这是必要的):**
 - OS: manjaro
 - Package: wechat-devtools-2-1.06.2209070-1-x86_64.pkg.tar.zst

**代码片段**

**额外的信息**

**Comment by freddong** [comment]
检查 `/opt/wechat-devtools` 目录看到 nwjs 和 package.nw两个目录是同级的,而非报错信息里的`nwjs/package.nw`.

暂时这样修正
```
sudo ln -s /opt/wechat-devtools/package.nw /opt/wechat-devtools/nwjs/package.nw
```

**Comment by msojocs** [comment]
过于久远，先关闭。
