### ISSUE TITLE
docker-compose up失败: cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory

### ISSUE THREAD

**Issue by wheelcomplex** [msojocs/wechat-web-devtools-linux#74]
**预先准备**
安装方法0,git 获取源码之后docker-compose up

**问题描述**

<pre>
wechat_devtools_1  | make: Entering directory '/workspace/package.nw/node_modules_tmp/node_modules/spdlog/build'
wechat_devtools_1  |   CXX(target) Release/obj.target/spdlog/src/main.o
wechat_devtools_1  |   CXX(target) Release/obj.target/spdlog/src/logger.o
wechat_devtools_1  |   SOLINK_MODULE(target) Release/obj.target/spdlog.node
wechat_devtools_1  |   COPY Release/spdlog.node
wechat_devtools_1  | make: Leaving directory '/workspace/package.nw/node_modules_tmp/node_modules/spdlog/build'
wechat_devtools_1  | gyp info ok 
wechat_devtools_1  |  remove unused files  
wechat_devtools_1  |  copy node files  
wechat_devtools_1  | Rebuilding wechat-devtools node modules Result Code: 0
wechat_devtools_1  | Patching wechat-devtools
wechat_devtools_1  | Patching Other
wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory
wechat_devtools_1  | 异常 Error: Command failed: /workspace/tools/fix-other.sh
wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory
wechat_devtools_1  | 
wechat_devtools_1  |     at checkExecSyncError (node:child_process:826:11)
wechat_devtools_1  |     at execSync (node:child_process:900:15)
wechat_devtools_1  |     at /workspace/tools/update-wechat-devtools-node:290:9
wechat_devtools_1  |     at new Promise (<anonymous>)
wechat_devtools_1  |     at patch_other (/workspace/tools/update-wechat-devtools-node:289:12)
wechat_devtools_1  |     at start (/workspace/tools/update-wechat-devtools-node:308:15)
wechat_devtools_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
wechat_devtools_1  |   status: 1,
wechat_devtools_1  |   signal: null,
wechat_devtools_1  |   output: [
wechat_devtools_1  |     null,
wechat_devtools_1  |     <Buffer 66 69 78 3a 20 77 65 62 76 69 65 77 20 6d 61 6e 61 67 65 72 0a 66 69 78 3a 20 77 63 63 2c 77 63 73 63 0a 74 6f 74 61 6c 20 31 32 31 0a 2d 72 77 2d 72 ... 468 more bytes>,
wechat_devtools_1  |     <Buffer 63 70 3a 20 63 61 6e 6e 6f 74 20 73 74 61 74 20 27 2f 77 6f 72 6b 73 70 61 63 65 2f 63 6f 6d 70 69 6c 65 72 2f 77 63 63 5f 6e 6f 64 65 2f 62 69 6e 27 ... 28 more bytes>
wechat_devtools_1  |   ],
wechat_devtools_1  |   pid: 13520,
wechat_devtools_1  |   stdout: <Buffer 66 69 78 3a 20 77 65 62 76 69 65 77 20 6d 61 6e 61 67 65 72 0a 66 69 78 3a 20 77 63 63 2c 77 63 73 63 0a 74 6f 74 61 6c 20 31 32 31 0a 2d 72 77 2d 72 ... 468 more bytes>,
wechat_devtools_1  |   stderr: <Buffer 63 70 3a 20 63 61 6e 6e 6f 74 20 73 74 61 74 20 27 2f 77 6f 72 6b 73 70 61 63 65 2f 63 6f 6d 70 69 6c 65 72 2f 77 63 63 5f 6e 6f 64 65 2f 62 69 6e 27 ... 28 more bytes>
wechat_devtools_1  | }
wechat_devtools_1  |  失败  command: node "$root_dir/tools/update-wechat-devtools-node" $TARGET_VERSION $@
wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:98
wechat_devtools_1  |   at 
wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
wechat_devtools_1  |   at docker/entrypoint:1
wechat_devtools_1  |   at 
wechat-web-devtools-linux_wechat_devtools_1 exited with code 255
</pre>

**问题复现**
docker-compose up
**期望的效果**
安装成功

**截屏**

**版本信息 (这是必要的):**
 - OS:
 <pre>
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
</pre>
 - Package: NA
 - Wine Version: NA

**代码片段**

**额外的信息**
unable to fix by:  npm install miniprogram-compiler

**Comment by pans0911** [comment]
> **预先准备** 安装方法0,git 获取源码之后docker-compose up
> 
> **问题描述**
> 
> wechat_devtools_1  | make: Entering directory '/workspace/package.nw/node_modules_tmp/node_modules/spdlog/build'
> wechat_devtools_1  |   CXX(target) Release/obj.target/spdlog/src/main.o
> wechat_devtools_1  |   CXX(target) Release/obj.target/spdlog/src/logger.o
> wechat_devtools_1  |   SOLINK_MODULE(target) Release/obj.target/spdlog.node
> wechat_devtools_1  |   COPY Release/spdlog.node
> wechat_devtools_1  | make: Leaving directory '/workspace/package.nw/node_modules_tmp/node_modules/spdlog/build'
> wechat_devtools_1  | gyp info ok 
> wechat_devtools_1  |  remove unused files  
> wechat_devtools_1  |  copy node files  
> wechat_devtools_1  | Rebuilding wechat-devtools node modules Result Code: 0
> wechat_devtools_1  | Patching wechat-devtools
> wechat_devtools_1  | Patching Other
> wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory
> wechat_devtools_1  | 异常 Error: Command failed: /workspace/tools/fix-other.sh
> wechat_devtools_1  | cp: cannot stat '/workspace/compiler/wcc_node/bin': No such file or directory
> wechat_devtools_1  | 
> wechat_devtools_1  |     at checkExecSyncError (node:child_process:826:11)
> wechat_devtools_1  |     at execSync (node:child_process:900:15)
> wechat_devtools_1  |     at /workspace/tools/update-wechat-devtools-node:290:9
> wechat_devtools_1  |     at new Promise ()
> wechat_devtools_1  |     at patch_other (/workspace/tools/update-wechat-devtools-node:289:12)
> wechat_devtools_1  |     at start (/workspace/tools/update-wechat-devtools-node:308:15)
> wechat_devtools_1  |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
> wechat_devtools_1  |   status: 1,
> wechat_devtools_1  |   signal: null,
> wechat_devtools_1  |   output: [
> wechat_devtools_1  |     null,
> wechat_devtools_1  |     ,
> wechat_devtools_1  |     
> wechat_devtools_1  |   ],
> wechat_devtools_1  |   pid: 13520,
> wechat_devtools_1  |   stdout: ,
> wechat_devtools_1  |   stderr: 
> wechat_devtools_1  | }
> wechat_devtools_1  |  失败  command: node "$root_dir/tools/update-wechat-devtools-node" $TARGET_VERSION $@
> wechat_devtools_1  |   at ./tools/setup-wechat-devtools-bash:98
> wechat_devtools_1  |   at 
> wechat_devtools_1  |  失败  command: ./tools/setup-wechat-devtools-bash
> wechat_devtools_1  |   at docker/entrypoint:1
> wechat_devtools_1  |   at 
> wechat-web-devtools-linux_wechat_devtools_1 exited with code 255
> **问题复现** docker-compose up **期望的效果** 安装成功
> 
> **截屏**
> 
> **版本信息 (这是必要的):**
> 
> * OS:
> 
> NAME="Ubuntu"
> VERSION="20.04.5 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.5 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> * Package: NA
> * Wine Version: NA
> 
> **代码片段**
> 
> **额外的信息** unable to fix by: npm install miniprogram-compiler

the same question

**Comment by msojocs** [comment]
已处理完毕
