### ISSUE TITLE
[兼容性问题] 部分node模块无法在Linux下使用

### ISSUE THREAD

**Issue by msojocs** [msojocs/wechat-web-devtools-linux#75]
## node模块

部分模块由于是Windows下限定闭源，无法复现其功能。

![image](https://user-images.githubusercontent.com/20937135/213845527-0f1e4a4e-8819-47e3-b128-9ee5d4e75096.png)

## 报错举例

![image](https://user-images.githubusercontent.com/20937135/213842122-c7f29384-9e59-4f18-9738-74296e593cf3.png)

**Comment by cnfczn** [comment]
闭源就有点过分了啊

**Comment by disburden** [comment]
之前版本就一直有这个问题,用起来好像正常,就不知道3个错误是什么意思,不知道有什么影响

**Comment by msojocs** [comment]
> 之前版本就一直有这个问题,用起来好像正常,就不知道3个错误是什么意思,不知道有什么影响

只要不用skyline功能应该就不会有影响

**Comment by msojocs** [comment]
这个 skyline 一堆bug 应该用的人不多

我连官方demo都跑不起来

![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/cd54c475-6b4f-43d8-b333-7e50df595698)
