### ISSUE TITLE
Manjaro下直接安装zst包，编译项目时报错：no such file or directory, stat '/opt/wechat-devtools/nwjs/package.nw/node_modules/wcc-exec'

### ISSUE THREAD

**Issue by smoothdvd** [msojocs/wechat-web-devtools-linux#76]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：不正常

**问题描述**
[ WXSS 文件编译错误] 
ENOENT: no such file or directory, stat '/opt/wechat-devtools/nwjs/package.nw/node_modules/wcc-exec'(env: Linux,mp,1.06.2301040; lib: 2.25.3)
WAServiceMainContext.js?t=wechat&s=1674317692444&v=2.25.3:1 [system] Subpackages: N/A
WAServiceMainContext.js?t=wechat&s=1674317692444&v=2.25.3:1 [system] LazyCodeLoading: false
[ WXML 文件编译错误] 
ENOENT: no such file or directory, stat '/opt/wechat-devtools/nwjs/package.nw/node_modules/wcc-exec'(env: Linux,mp,1.06.2301040; lib: 2.25.3)

**问题复现**
manjaro下直接安装zst包
运行一个小程序项目

**期望的效果**

正常编译

**截屏**

**版本信息 (这是必要的):**
 - OS: e.g. manjaro 22.0.0
 - Package: [wechat-devtools-2-1.06.2301040-1-x86_64.pkg.tar.zst](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2301040-1/wechat-devtools-2-1.06.2301040-1-x86_64.pkg.tar.zst)

**代码片段**

**额外的信息**

**Comment by msojocs** [comment]
![Uploading image.png…]()
我直接装的，没有复现

**Comment by gmmp** [comment]
![image](https://user-images.githubusercontent.com/16728548/215055487-7a61b2d3-5f88-4019-aea0-f279d4d531b3.png)
遇到了一样的问题

**Comment by gmmp** [comment]
大佬四天前已经修复这个问题了，https://github.com/msojocs/wechat-web-devtools-linux/commit/035ffe756fb652e9205a74b7a87e2a25bbd09cb7。
换成 continuous版本就可以了。 https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/continuous
