### ISSUE TITLE
lazyCodeLoading: 'requiredComponents'配置项会导致小程序白屏

### ISSUE THREAD

**Issue by smoothdvd** [msojocs/wechat-web-devtools-linux#77]
**预先准备**

**问题描述**

小程序白屏并有报错

[WXML Runtime warning] ./pages/index/index.wxml
 Path `../../base.wxml` not found from `./pages/index/index.wxml`.
> 1 | <import src="../../base.wxml"/>
    | ^
  2 | <template is="taro_tmpl" data="{{root:root}}" />
[WXML Runtime warning] ./pages/index/index.wxml
 Template `taro_tmpl` not found.
  1 | <import src="../../base.wxml"/>
> 2 | <template is="taro_tmpl" data="{{root:root}}" />

**问题复现**

1、taro init，初始化官方react模板
2、app.config.ts中添加lazyCodeLoading: 'requiredComponents'配置项
3、打包小程序

**期望的效果**

支持lazyCodeLoading

**截屏**

**版本信息 (这是必要的):**
 - OS: e.g. manjaro
 - Package: wechat-devtools-2-1.06.2301040-0-x86_64.pkg.tar.zst

**Comment by msojocs** [comment]
已复现
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/f020af96-8fad-4bb9-90fb-7dd125c483c2)
