### ISSUE TITLE
打开项目后，弹窗提示：couldn't start client skyline style server 

### ISSUE THREAD

**Issue by cnfczn** [msojocs/wechat-web-devtools-linux#78]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目：已删除，并重新打开
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：能够复现

**问题描述**
打开项目后，弹窗提示：连着3个提示框
1. couldn't start client skyline style server 
2. A request has failed.See the output for more information.
点击Go to output 没有提示.

3. Request initialize failed with message:
/home/user/.config/wechat-devtools/WeNativeModules/use/node-float-pigment-css/float-pigment-css-for-nodejs.onde: invalid ELF header

**问题复现**
1. 新建项目-javascript-基础模板
2. 等待加载完毕
3. 出现弹窗提示

**期望的效果**
没有弹窗提示，错误能够修正

**截屏**
![image](https://user-images.githubusercontent.com/1464805/220018289-473ec8da-e4bd-4cb3-8ca3-163a3837548b.png)
![image](https://user-images.githubusercontent.com/1464805/220018325-e133a82f-e4fc-407b-9fba-bb13c17a11f1.png)
![image](https://user-images.githubusercontent.com/1464805/220018378-5a744f3c-9c7f-45f7-a232-ce33445bdae6.png)

**版本信息 (这是必要的):**
 - OS: gentoo
 - DE: xfce 4.18
 - Package: e.g. WeChat_Dev_Tools_v1.06.2301040-1_x86_64_linux.AppImage
 - Wine Version: 未安装

**额外的信息**
WeChat_Dev_Tools_v1.06.2209070-1_x86_64_linux.AppImage
WeChat_Dev_Tools_v1.06.2301040-1_x86_64_linux.AppImage
两个版本都有这个问题

WeChat_Dev_Tools_v1.06.2206090-2_x86_64_no_wine.AppImage
这个版本不存在这个问题

**Comment by msojocs** [comment]
#75
