### ISSUE TITLE
[已启用] 基于CPP的Linux原生编译器

### ISSUE THREAD

**Issue by msojocs** [msojocs/wechat-web-devtools-linux#81]
反编译搞得，已复现大部分功能 >_<

https://github.com/msojocs/wx-compiler/tree/cpp

还存在部分地方用例没跑到，所以未复现。

![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/b6e26f43-df25-46c2-bc65-8803b383ccab)

**Comment by msojocs** [comment]
目前比较顺利

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/da750ebc-b76e-4d1c-9697-79ab80097955)

记录一下

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/5be633ed-462c-4867-acd5-023ce5e88bef)

nice

**Comment by msojocs** [comment]
记录一下：在弄wcsc的编译器，有点头大

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/88c7ae5b-4d74-4692-87f4-e031e8a54b88)

剩下就是查缺补漏了

**Comment by imic07** [comment]
牛皮
