### ISSUE TITLE
iOS真机调试一直是白屏，开发者工具里Wxml里是空白的

### ISSUE THREAD

**Issue by Black-Jacki** [msojocs/wechat-web-devtools-linux#82]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；是的
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：不正常

**问题描述**

iOS真机调试一直是白屏，开发者工具里Wxml里是空白的

**问题复现**

1. 打开项目
2. 点击 '真机调试'
3. iPhone扫码调试

**期望的效果**

能正确显示UI并且能调试程序

**截屏**

就是白屏
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/63303518/6336cf8d-7e68-48d4-b0d2-6c75f655360f)

![30c16eebe50f3a39b334436cf31d16b](https://github.com/msojocs/wechat-web-devtools-linux/assets/63303518/52a0183b-5319-4320-9ac9-7c49e4c6520e)

**版本信息 (这是必要的):**
Ubuntu22.04LTS
开发者工具[io.github.msojocs.wechat-devtools-linux_1.06.2306020-1_amd64.deb](https://github.com/msojocs/wechat-web-devtools-linux/releases/download/v1.06.2306020-1/io.github.msojocs.wechat-devtools-linux_1.06.2306020-1_amd64.deb)
之前版本就有这个问题，好像一开始好多个版本前是可以的

**代码片段**

**额外的信息**

**Comment by Black-Jacki** [comment]
看起来像是没有发送http请求导致的

**Comment by msojocs** [comment]
等我cpp版本编译器整成了再说

**Comment by disburden** [comment]
> 

虽然不知道cpp编译器是做什么用的,但是感觉很厉害的样子,加油.
是不是这个编译器出来了之后,将来要是微信开发工具有新版本我们自己更新到最新版本?
