### ISSUE TITLE
华为银河麒麟系统，linux的arm64架构下构筑失败

### ISSUE THREAD

**Issue by houjl001** [msojocs/wechat-web-devtools-linux#83]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常

**问题描述**

docker下构筑失败
**问题复现**

执行docker-compose up 后报错

pulling wechat_devtools (jiyecafe/wechat-devtools-build:v3)...
v3: Pulling from jiyecafe/wechat-devtools-build
58690f9b18fc: Pull complete
b51569e7c507: Pull complete
da8ef40b9eca: Pull complete
fb15d46c38dc: Pull complete
ce568104c5b3: Pull complete
5f4535f17dfa: Pull complete
d7ddda710afd: Pull complete
Digest: sha256:bdb56bf7575728838d756a641737176f04c0b966ca07c2941bda0d9cceba65c5
Status: Downloaded newer image for jiyecafe/wechat-devtools-build:v3
Creating wechat-web-devtools-linux_wechat_devtools_1 ... done
Attaching to wechat-web-devtools-linux_wechat_devtools_1
wechat_devtools_1  | standard_init_linux.go:228: exec user process caused: no such file or directory
wechat-web-devtools-linux_wechat_devtools_1 exited with code 1

**期望的效果**

大佬看下怎么解决，是否可以构筑一个arm64架构的版本出来，求求了
快被垃圾国企逼疯了

**截屏**

**版本信息 (这是必要的):**
 - OS: e.g. manjaro
 - Package: e.g. xxx_wine.tar.gz
 - Wine Version: e.g. 7 可选

**代码片段**

**额外的信息**

**Comment by msojocs** [comment]
应该是架构不兼容的问题，我那个 `docker` 应该只支持x86。
有空再弄一下。
