### ISSUE TITLE
useExtendedLib (weui) 无法使用

### ISSUE THREAD

**Issue by jilen** [msojocs/wechat-web-devtools-linux#86]
声明
```json
"useExtendedLib": {
    "weui": true
  }
```
```
"usingComponents": {
    "mp-dialog": "/miniprogram_npm/weui-miniprogram/dialog/dialog"
  }
```
提示依赖异常，显示空白页面
windows开发者工具可以正常运行

**Comment by msojocs** [comment]
有没有demo

**Comment by jilen** [comment]
https://developers.weixin.qq.com/s/sfUsEemj7chI 可以通过这个代码片段导入到开发者工具测试

来源： https://github.com/wechat-miniprogram/weui-miniprogram/issues/96#issuecomment-626285151

**Comment by jilen** [comment]
仔细测试后不是useExtendedLib的问题，实际上所有工程都无法打开，重新安装后就行了。。。
