### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by BarryPYing** [msojocs/wechat-web-devtools-linux#89]
**问题描述**
更新版本后，编译小程序报错，已删除~./.config/wechat-devetools配置重新登录，编译项目报错如下：
message：自动真机调试 Error: terminate called after throwing an instance of 'char const*'
编译 .wxml 文件错误，错误信息如上，可在控制台查看更详细信息
ideVersion: 1.06.2307260
osType: linux-x64(ubuntu 22)
time: 2023-09-13 10:49:11
**问题复现**
直接编译项目即可

**期望的效果**

**截屏**

![2023-09-13_10-58](https://github.com/msojocs/wechat-web-devtools-linux/assets/130635329/36cf0875-7f91-4a63-bde8-bc8ed463516c)

**版本信息 (这是必要的):**
 - OS: e.g. ubuntu 22
 - Package: io.github.msojocs.wechat-devtools-linux_1.06.2307260-1_amd64.deb
 - Wine Version: 6.0.3

**Comment by msojocs** [comment]
建议提供复现demo

**Comment by msojocs** [comment]
目前有部分功能我没有实现，因为我的测试项目没跑到那些部分。
