### ISSUE TITLE
编译问题，无法编译WXSS文件

### ISSUE THREAD

**Issue by xifan2032** [msojocs/wechat-web-devtools-linux#90]
[ WXML 文件编译错误] 
/home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc)
/home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc)
/home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc)
/home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcc)
(env: Linux,mp,1.06.2307260; lib: 2.19.4)

/home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcsc: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/xifan/.config/wechat-devtools/WeNativeModules/use/wcc-exec/wcsc)(env: Linux,mp,1.06.2307260; lib: 2.19.4)

操作系统：deepin v20.9 社区板

**Comment by msojocs** [comment]
已复现

**Comment by xifan2032** [comment]
怎么解决这个问题呢，WXML 文件编译错误

**Comment by msojocs** [comment]
快的自己编译
慢的等我编译

**Comment by msojocs** [comment]
草，编译器好像炸了

**Comment by msojocs** [comment]
短期内可能修不好

**Comment by msojocs** [comment]
你那边方便给一下这两条命令的结果吗？
```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_
```

**Comment by xifan2032** [comment]
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBC
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBC_2.2.5
GLIBC_2.3
GLIBC_2.14
GLIBC_2.18
GLIBC_2.16
GLIBC_2.17
GLIBC_2.3.2
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by xifan2032** [comment]
strings /lib/x86_64-linux-gnu/libc.so.6 | grep GLIBC_
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_2.18
GLIBC_2.22
GLIBC_2.23
GLIBC_2.24
GLIBC_2.25
GLIBC_2.26
GLIBC_2.27
GLIBC_2.28
GLIBC_PRIVATE

**Comment by msojocs** [comment]
覆盖一下看看
`file:///opt/apps/io.github.msojocs.wechat-devtools-linux/files/bin/package.nw/node_modules/wcc-exec`
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/8ddea440-1eaf-44bd-ba6b-2a01e2bef8ec)


[wcc-wcsc.zip](https://github.com/msojocs/wechat-web-devtools-linux/files/12705576/wcc-wcsc.zip)

**Comment by xifan2032** [comment]
解决了，谢谢
