### ISSUE TITLE
fedora38 界面乱码

### ISSUE THREAD

**Issue by kerrer** [msojocs/wechat-web-devtools-linux#92]
**问题描述**
界面乱码

[乱码界面图片](https://pcsdata.baidu.com/thumbnail/2cae816d4q94a0eb80e80ae360ebb164?fid=3543660744-16051585-492972015057938&rt=pr&sign=FDTAER-yUdy3dSFZ0SVxtzShv1zcMqd-r%2BHfY1nr6XCTdfNW%2Bb4W1gTeMOc%3D&expires=2h&chkv=0&chkbd=0&chkpc=&dp-logid=509965926920721621&dp-callid=0&time=1695873600&bus_no=26&size=c1600_u1600&quality=100&vuk=-&ft=video)

**版本信息 (这是必要的):**
 - OS:  fedora38
 - Package:  WeChat_Dev_Tools_v1.06.2307260-2_x86_64_linux.AppImage
 - Wine Version

**Comment by msojocs** [comment]
怎么图都不会发

**Comment by msojocs** [comment]
按Ctrl + V栋？

**Comment by msojocs** [comment]
Log: 

![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/b1052446-d99f-44dc-a6ca-d6e779ee49d9)

demo正常，方块字具体原因待查。

方块字不是乱码，疑似字体没找到。

**Comment by msojocs** [comment]
已确认是字体问题：

![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/af1ef7a5-e3e1-43d6-bec5-63637dd748c3)

**Comment by msojocs** [comment]
装上微软雅黑就行了
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/51537940-5bf6-4028-ad1c-a4ca9dead8a8)

**Comment by wencan** [comment]
fedora 40 

AppImage试了多个版本，也尝试安装字体，都没能解决字体问题

最后自己编译安装，解决了字体问题
但零售电商模板打开报错

**Comment by shao4598** [comment]
我有解决方案了。
原因是 Fedora 的 sans-serif 默认不是中文字体。
解决方案如下：
1. 新建文件 ```~/.config/fontconfig/fonts.conf```。
2. 按如下配置默认字体，```<string/>``` 里的字体按个人喜好选择，只要保证是中文字体即可。
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <match>
    <edit name="family" mode="prepend">
      <string>PingFang SC</string>
    </edit>
  </match>
</fontconfig>
```
3. 保存并退出fonts.conf。
4. 刷新字体配置缓存。
```shell
$ fc-cache -f -v
```

**Comment by liinyun** [comment]
> 我有解决方案了。 原因是 Fedora 的 sans-serif 默认不是中文字体。 解决方案如下：
> 
> 1. 新建文件 `~/.config/fontconfig/fonts.conf`。
> 2. 按如下配置默认字体，`<string/>` 里的字体按个人喜好选择，只要保证是中文字体即可。
> 
> <?xml version='1.0'?>
> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
> <fontconfig>
>   <match>
>     <edit name="family" mode="prepend">
>       <string>PingFang SC</string>
>     </edit>
>   </match>
> </fontconfig>
> 3. 保存并退出fonts.conf。
> 4. 刷新字体配置缓存。
> 
> $ fc-cache -f -v

老哥，我用的微软雅黑，还是不能正常显示，我的系统也是fedora

**Comment by liinyun** [comment]
> 装上微软雅黑就行了 ![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/51537940-5bf6-4028-ad1c-a4ca9dead8a8)

我装上了，你这个页面也是正常显示的，但是进去以后就不行了

![Image](https://github.com/user-attachments/assets/2028ee1c-2cdd-4e9d-b154-ee94d36834ee)

**Comment by msojocs** [comment]
@liinyun 试试文泉驿字体

**Comment by liinyun** [comment]
> @liinyun 试试文泉驿字体

弄好了，是我的微软雅黑不全🌚应该是某些盗版网站下载的。我把系统的微软雅黑删了重装就行了。那个上面那个老哥的配置可以再改进一下。他那么搞了后整个系统都会自动用中文fallback 别的软件直接换不了字体了。可以配置只在你这个软件中用微软雅黑fallback。我等下发一下配置

**Comment by senseab** [comment]
需要配置一个 fontconfig，强制 `Segoe WPC` 以雅黑字体显示

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <!-- 强制 Segoe WPC 使用 Microsoft YaHei -->
    <match target="pattern">
        <test name="family" qual="any">
            <string>Segoe WPC</string>
        </test>
        <edit name="family" mode="assign" binding="strong">
            <string>Microsoft YaHei</string>
        </edit>
    </match>
</fontconfig>
```

```xml
<!-- 对于没有 Ubuntu 字体的系统，可以使用这个规则 -->
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
    <!-- 强制 Ubuntu 使用 Microsoft YaHei -->
    <match target="pattern">
        <test name="family" qual="any">
            <string>Ubuntu</string>
        </test>
        <edit name="family" mode="assign" binding="strong">
            <string>Microsoft YaHei</string>
        </edit>
    </match>
</fontconfig>
```
