### ISSUE TITLE
$gwx 的函数错误

### ISSUE THREAD

**Issue by 2715851270** [msojocs/wechat-web-devtools-linux#97]
**预先准备**
1. 删除 `~/.config/wechat-devtools` 目录，重新打开项目（若发布 `issue` 即默认阁下执行了此操作且问题没有解决）；
2. HelloWorld是否正常（登录状态新建默认项目,执行复现步骤）：正常/不正常
3. ***注意：如果你的问题是编译器错误，那么请提供可复现的demo，否则会被直接关闭。***

**问题描述**
加载ThorUI的实例项目时， 提示$gwx is not a function ， 然后项目打不开，自己写的其他项目正常打开

**问题复现**

下载项目文件： 
链接: https://pan.baidu.com/s/1bRBQ-dtvXOueoCiufBOsaA?pwd=1234 提取码: 1234
1. 打开项目  
2. 信任并运行
3. 看到问题
4. 

**期望的效果**

期望能正常运行起来。 
**截屏**

![1699452968969](https://github.com/msojocs/wechat-web-devtools-linux/assets/46163839/0811ce79-4efe-48a2-8c9d-0e2fe72b1771)

**版本信息 (这是必要的):**
 - OS: e.g. manjaro
 - Package: e.g. xxx_wine.tar.gz
 - Wine Version: e.g. 7 可选
版本信息： 1.06.2308310-1
WeChat_Dev_Tools_v1.06.2308310-1_x86_64_linux.AppImage

**代码片段**

**额外的信息**

**Comment by msojocs** [comment]
感谢提供demo，已复现，将会进行修复。

**Comment by msojocs** [comment]
![image](https://github.com/msojocs/wechat-web-devtools-linux/assets/20937135/502440bc-1592-4613-9d00-2773f47b47ec)

修好了，等我发个版

**Comment by msojocs** [comment]
https://github.com/msojocs/wechat-web-devtools-linux/releases/tag/v1.06.2308310-2
试一下最新版

**Comment by 2715851270** [comment]
非常感谢， 可以了。
